{ Unit Floria.XCB.Keysyms — Blaise binding for library 'xcb-keysyms'.
  Generated by blaise-bindgen — DO NOT EDIT.
  Regenerate with:  bindgen --header <header.h> --unit Floria.XCB.Keysyms --lib xcb-keysyms }

unit Floria.XCB.Keysyms;
{$mode objfpc}{$H+}

interface

uses
  Floria.XCB;

type
  Pxcb_key_symbols_t = ^xcb_key_symbols_t;
  Pxcb_connection_t = ^xcb_connection_t;
  Pxcb_keycode_t = ^xcb_keycode_t;
  Pxcb_key_press_event_t = ^xcb_key_press_event_t;
  Pxcb_key_release_event_t = ^xcb_key_release_event_t;
  Pxcb_mapping_notify_event_t = ^xcb_mapping_notify_event_t;
  _XCBKeySymbols = record end; { opaque }
  xcb_key_symbols_t = _XCBKeySymbols;

function xcb_key_symbols_alloc(c: Pxcb_connection_t): Pxcb_key_symbols_t; cdecl; external 'xcb-keysyms' name 'xcb_key_symbols_alloc';
procedure xcb_key_symbols_free(syms: Pxcb_key_symbols_t); cdecl; external 'xcb-keysyms' name 'xcb_key_symbols_free';
{ xcb_key_symbols_get_keysym: skipped — return type 'xcb_keysym_t' comes from a filtered-out header }
{ xcb_key_symbols_get_keycode: skipped — parameter type 'xcb_keysym_t' comes from a filtered-out header }
{ xcb_key_press_lookup_keysym: skipped — return type 'xcb_keysym_t' comes from a filtered-out header }
{ xcb_key_release_lookup_keysym: skipped — return type 'xcb_keysym_t' comes from a filtered-out header }
function xcb_refresh_keyboard_mapping(syms: Pxcb_key_symbols_t; event: Pxcb_mapping_notify_event_t): Integer; cdecl; external 'xcb-keysyms' name 'xcb_refresh_keyboard_mapping';
{ xcb_is_keypad_key: skipped — parameter type 'xcb_keysym_t' comes from a filtered-out header }
{ xcb_is_private_keypad_key: skipped — parameter type 'xcb_keysym_t' comes from a filtered-out header }
{ xcb_is_cursor_key: skipped — parameter type 'xcb_keysym_t' comes from a filtered-out header }
{ xcb_is_pf_key: skipped — parameter type 'xcb_keysym_t' comes from a filtered-out header }
{ xcb_is_function_key: skipped — parameter type 'xcb_keysym_t' comes from a filtered-out header }
{ xcb_is_misc_function_key: skipped — parameter type 'xcb_keysym_t' comes from a filtered-out header }
{ xcb_is_modifier_key: skipped — parameter type 'xcb_keysym_t' comes from a filtered-out header }

implementation

end.
