{ Unit Floria.XCB.Shape — Blaise binding for library 'xcb-shape'.
  Generated by blaise-bindgen — DO NOT EDIT.
  Regenerate with:  bindgen --header <header.h> --unit Floria.XCB.Shape --lib xcb-shape }

unit Floria.XCB.Shape;
{$mode objfpc}{$H+}

interface

uses
  Floria.XCB;

type
  Pxcb_shape_op_t = ^xcb_shape_op_t;
  Pxcb_shape_kind_t = ^xcb_shape_kind_t;
  Pxcb_shape_op_iterator_t = ^xcb_shape_op_iterator_t;
  Pxcb_shape_kind_iterator_t = ^xcb_shape_kind_iterator_t;
  Pxcb_connection_t = ^xcb_connection_t;
  Pxcb_shape_query_version_reply_t = ^xcb_shape_query_version_reply_t;
  Pxcb_generic_error_t = ^xcb_generic_error_t;
  PPxcb_generic_error_t = ^Pxcb_generic_error_t;
  Pxcb_rectangle_t = ^xcb_rectangle_t;
  Pxcb_shape_rectangles_request_t = ^xcb_shape_rectangles_request_t;
  Pxcb_shape_query_extents_reply_t = ^xcb_shape_query_extents_reply_t;
  Pxcb_shape_input_selected_reply_t = ^xcb_shape_input_selected_reply_t;
  Pxcb_shape_get_rectangles_reply_t = ^xcb_shape_get_rectangles_reply_t;
  xcb_shape_op_t = Byte;
  xcb_shape_op_iterator_t = record
    data: Pxcb_shape_op_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_shape_kind_t = Byte;
  xcb_shape_kind_iterator_t = record
    data: Pxcb_shape_kind_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_shape_so_t = Integer;
  xcb_shape_sk_t = Integer;
  xcb_shape_notify_event_t = record
    response_type: Byte;
    shape_kind: xcb_shape_kind_t;
    sequence: Word;
    affected_window: xcb_window_t;
    extents_x: SmallInt;
    extents_y: SmallInt;
    extents_width: Word;
    extents_height: Word;
    server_time: xcb_timestamp_t;
    shaped: Byte;
    pad0: array[0..10] of Byte;
  end;
  xcb_shape_query_version_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_shape_query_version_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
  end;
  xcb_shape_query_version_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    major_version: Word;
    minor_version: Word;
  end;
  xcb_shape_rectangles_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    operation: xcb_shape_op_t;
    destination_kind: xcb_shape_kind_t;
    ordering: Byte;
    pad0: Byte;
    destination_window: xcb_window_t;
    x_offset: SmallInt;
    y_offset: SmallInt;
  end;
  xcb_shape_mask_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    operation: xcb_shape_op_t;
    destination_kind: xcb_shape_kind_t;
    pad0: array[0..1] of Byte;
    destination_window: xcb_window_t;
    x_offset: SmallInt;
    y_offset: SmallInt;
    source_bitmap: xcb_pixmap_t;
  end;
  xcb_shape_combine_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    operation: xcb_shape_op_t;
    destination_kind: xcb_shape_kind_t;
    source_kind: xcb_shape_kind_t;
    pad0: Byte;
    destination_window: xcb_window_t;
    x_offset: SmallInt;
    y_offset: SmallInt;
    source_window: xcb_window_t;
  end;
  xcb_shape_offset_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    destination_kind: xcb_shape_kind_t;
    pad0: array[0..2] of Byte;
    destination_window: xcb_window_t;
    x_offset: SmallInt;
    y_offset: SmallInt;
  end;
  xcb_shape_query_extents_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_shape_query_extents_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    destination_window: xcb_window_t;
  end;
  xcb_shape_query_extents_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    bounding_shaped: Byte;
    clip_shaped: Byte;
    pad1: array[0..1] of Byte;
    bounding_shape_extents_x: SmallInt;
    bounding_shape_extents_y: SmallInt;
    bounding_shape_extents_width: Word;
    bounding_shape_extents_height: Word;
    clip_shape_extents_x: SmallInt;
    clip_shape_extents_y: SmallInt;
    clip_shape_extents_width: Word;
    clip_shape_extents_height: Word;
  end;
  xcb_shape_select_input_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    destination_window: xcb_window_t;
    enable: Byte;
    pad0: array[0..2] of Byte;
  end;
  xcb_shape_input_selected_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_shape_input_selected_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    destination_window: xcb_window_t;
  end;
  xcb_shape_input_selected_reply_t = record
    response_type: Byte;
    enabled: Byte;
    sequence: Word;
    length: Cardinal;
  end;
  xcb_shape_get_rectangles_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_shape_get_rectangles_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    window: xcb_window_t;
    source_kind: xcb_shape_kind_t;
    pad0: array[0..2] of Byte;
  end;
  xcb_shape_get_rectangles_reply_t = record
    response_type: Byte;
    ordering: Byte;
    sequence: Word;
    length: Cardinal;
    rectangles_len: Cardinal;
    pad0: array[0..19] of Byte;
  end;

const
  XCB_SHAPE_SO_SET = 0;
  XCB_SHAPE_SO_UNION = 1;
  XCB_SHAPE_SO_INTERSECT = 2;
  XCB_SHAPE_SO_SUBTRACT = 3;
  XCB_SHAPE_SO_INVERT = 4;
  XCB_SHAPE_SK_BOUNDING = 0;
  XCB_SHAPE_SK_CLIP = 1;
  XCB_SHAPE_SK_INPUT = 2;
  XCB_SHAPE_MAJOR_VERSION = 1;
  XCB_SHAPE_MINOR_VERSION = 1;
  XCB_SHAPE_NOTIFY = 0;

procedure xcb_shape_op_next(i: Pxcb_shape_op_iterator_t); cdecl; external 'xcb-shape' name 'xcb_shape_op_next';
{ xcb_shape_op_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_shape_kind_next(i: Pxcb_shape_kind_iterator_t); cdecl; external 'xcb-shape' name 'xcb_shape_kind_next';
{ xcb_shape_kind_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_shape_query_version(c: Pxcb_connection_t): xcb_shape_query_version_cookie_t; cdecl; external 'xcb-shape' name 'xcb_shape_query_version';
function xcb_shape_query_version_unchecked(c: Pxcb_connection_t): xcb_shape_query_version_cookie_t; cdecl; external 'xcb-shape' name 'xcb_shape_query_version_unchecked';
function xcb_shape_query_version_reply(c: Pxcb_connection_t; cookie: xcb_shape_query_version_cookie_t; e: PPxcb_generic_error_t): Pxcb_shape_query_version_reply_t; cdecl; external 'xcb-shape' name 'xcb_shape_query_version_reply';
function xcb_shape_rectangles_sizeof(_buffer: Pointer; rectangles_len: Cardinal): Integer; cdecl; external 'xcb-shape' name 'xcb_shape_rectangles_sizeof';
{ xcb_shape_rectangles_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_shape_rectangles: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_shape_rectangles_rectangles(R: Pxcb_shape_rectangles_request_t): Pxcb_rectangle_t; cdecl; external 'xcb-shape' name 'xcb_shape_rectangles_rectangles';
function xcb_shape_rectangles_rectangles_length(R: Pxcb_shape_rectangles_request_t): Integer; cdecl; external 'xcb-shape' name 'xcb_shape_rectangles_rectangles_length';
{ xcb_shape_rectangles_rectangles_iterator: skipped — return type 'xcb_rectangle_iterator_t' comes from a filtered-out header }
{ xcb_shape_mask_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_shape_mask: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_shape_combine_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_shape_combine: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_shape_offset_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_shape_offset: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_shape_query_extents: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
{ xcb_shape_query_extents_unchecked: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
function xcb_shape_query_extents_reply(c: Pxcb_connection_t; cookie: xcb_shape_query_extents_cookie_t; e: PPxcb_generic_error_t): Pxcb_shape_query_extents_reply_t; cdecl; external 'xcb-shape' name 'xcb_shape_query_extents_reply';
{ xcb_shape_select_input_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_shape_select_input: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_shape_input_selected: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
{ xcb_shape_input_selected_unchecked: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
function xcb_shape_input_selected_reply(c: Pxcb_connection_t; cookie: xcb_shape_input_selected_cookie_t; e: PPxcb_generic_error_t): Pxcb_shape_input_selected_reply_t; cdecl; external 'xcb-shape' name 'xcb_shape_input_selected_reply';
function xcb_shape_get_rectangles_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-shape' name 'xcb_shape_get_rectangles_sizeof';
{ xcb_shape_get_rectangles: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
{ xcb_shape_get_rectangles_unchecked: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
function xcb_shape_get_rectangles_rectangles(R: Pxcb_shape_get_rectangles_reply_t): Pxcb_rectangle_t; cdecl; external 'xcb-shape' name 'xcb_shape_get_rectangles_rectangles';
function xcb_shape_get_rectangles_rectangles_length(R: Pxcb_shape_get_rectangles_reply_t): Integer; cdecl; external 'xcb-shape' name 'xcb_shape_get_rectangles_rectangles_length';
{ xcb_shape_get_rectangles_rectangles_iterator: skipped — return type 'xcb_rectangle_iterator_t' comes from a filtered-out header }
function xcb_shape_get_rectangles_reply(c: Pxcb_connection_t; cookie: xcb_shape_get_rectangles_cookie_t; e: PPxcb_generic_error_t): Pxcb_shape_get_rectangles_reply_t; cdecl; external 'xcb-shape' name 'xcb_shape_get_rectangles_reply';

implementation

end.
