{ Unit Floria.XCB.SHM — Blaise binding for library 'xcb-shm'.
  Generated by blaise-bindgen — DO NOT EDIT.
  Regenerate with:  bindgen --header <header.h> --unit Floria.XCB.SHM --lib xcb-shm }

unit Floria.XCB.SHM;
{$mode objfpc}{$H+}

interface

uses
  Floria.XCB;

type
  Pxcb_shm_seg_t = ^xcb_shm_seg_t;
  Pxcb_shm_seg_iterator_t = ^xcb_shm_seg_iterator_t;
  Pxcb_connection_t = ^xcb_connection_t;
  Pxcb_shm_query_version_reply_t = ^xcb_shm_query_version_reply_t;
  Pxcb_generic_error_t = ^xcb_generic_error_t;
  PPxcb_generic_error_t = ^Pxcb_generic_error_t;
  Pxcb_shm_get_image_reply_t = ^xcb_shm_get_image_reply_t;
  Pxcb_shm_create_segment_reply_t = ^xcb_shm_create_segment_reply_t;
  PInteger = ^Integer;
  xcb_shm_seg_t = Cardinal;
  xcb_shm_seg_iterator_t = record
    data: Pxcb_shm_seg_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_shm_completion_event_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    drawable: xcb_drawable_t;
    minor_event: Word;
    major_event: Byte;
    pad1: Byte;
    shmseg: xcb_shm_seg_t;
    offset: Cardinal;
  end;
  xcb_shm_bad_seg_error_t = Pointer; { unresolved C type 'xcb_value_error_t' — declared in a filtered-out header }
  xcb_shm_query_version_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_shm_query_version_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
  end;
  xcb_shm_query_version_reply_t = record
    response_type: Byte;
    shared_pixmaps: Byte;
    sequence: Word;
    length: Cardinal;
    major_version: Word;
    minor_version: Word;
    uid: Word;
    gid: Word;
    pixmap_format: Byte;
    pad0: array[0..14] of Byte;
  end;
  xcb_shm_attach_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    shmseg: xcb_shm_seg_t;
    shmid: Cardinal;
    read_only: Byte;
    pad0: array[0..2] of Byte;
  end;
  xcb_shm_detach_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    shmseg: xcb_shm_seg_t;
  end;
  xcb_shm_put_image_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    drawable: xcb_drawable_t;
    gc: xcb_gcontext_t;
    total_width: Word;
    total_height: Word;
    src_x: Word;
    src_y: Word;
    src_width: Word;
    src_height: Word;
    dst_x: SmallInt;
    dst_y: SmallInt;
    depth: Byte;
    format: Byte;
    send_event: Byte;
    pad0: Byte;
    shmseg: xcb_shm_seg_t;
    offset: Cardinal;
  end;
  xcb_shm_get_image_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_shm_get_image_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    drawable: xcb_drawable_t;
    x: SmallInt;
    y: SmallInt;
    width: Word;
    height: Word;
    plane_mask: Cardinal;
    format: Byte;
    pad0: array[0..2] of Byte;
    shmseg: xcb_shm_seg_t;
    offset: Cardinal;
  end;
  xcb_shm_get_image_reply_t = record
    response_type: Byte;
    depth: Byte;
    sequence: Word;
    length: Cardinal;
    visual: xcb_visualid_t;
    size: Cardinal;
  end;
  xcb_shm_create_pixmap_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    pid: xcb_pixmap_t;
    drawable: xcb_drawable_t;
    width: Word;
    height: Word;
    depth: Byte;
    pad0: array[0..2] of Byte;
    shmseg: xcb_shm_seg_t;
    offset: Cardinal;
  end;
  xcb_shm_attach_fd_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    shmseg: xcb_shm_seg_t;
    read_only: Byte;
    pad0: array[0..2] of Byte;
  end;
  xcb_shm_create_segment_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_shm_create_segment_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    shmseg: xcb_shm_seg_t;
    size: Cardinal;
    read_only: Byte;
    pad0: array[0..2] of Byte;
  end;
  xcb_shm_create_segment_reply_t = record
    response_type: Byte;
    nfd: Byte;
    sequence: Word;
    length: Cardinal;
    pad0: array[0..23] of Byte;
  end;

const
  XCB_SHM_MAJOR_VERSION = 1;
  XCB_SHM_MINOR_VERSION = 2;
  XCB_SHM_COMPLETION = 0;
  XCB_SHM_BAD_SEG = 0;

procedure xcb_shm_seg_next(i: Pxcb_shm_seg_iterator_t); cdecl; external 'xcb-shm' name 'xcb_shm_seg_next';
{ xcb_shm_seg_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_shm_query_version(c: Pxcb_connection_t): xcb_shm_query_version_cookie_t; cdecl; external 'xcb-shm' name 'xcb_shm_query_version';
function xcb_shm_query_version_unchecked(c: Pxcb_connection_t): xcb_shm_query_version_cookie_t; cdecl; external 'xcb-shm' name 'xcb_shm_query_version_unchecked';
function xcb_shm_query_version_reply(c: Pxcb_connection_t; cookie: xcb_shm_query_version_cookie_t; e: PPxcb_generic_error_t): Pxcb_shm_query_version_reply_t; cdecl; external 'xcb-shm' name 'xcb_shm_query_version_reply';
{ xcb_shm_attach_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_shm_attach: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_shm_detach_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_shm_detach: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_shm_put_image_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_shm_put_image: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_shm_get_image: skipped — parameter type 'xcb_drawable_t' comes from a filtered-out header }
{ xcb_shm_get_image_unchecked: skipped — parameter type 'xcb_drawable_t' comes from a filtered-out header }
function xcb_shm_get_image_reply(c: Pxcb_connection_t; cookie: xcb_shm_get_image_cookie_t; e: PPxcb_generic_error_t): Pxcb_shm_get_image_reply_t; cdecl; external 'xcb-shm' name 'xcb_shm_get_image_reply';
{ xcb_shm_create_pixmap_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_shm_create_pixmap: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_shm_attach_fd_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_shm_attach_fd: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_shm_create_segment(c: Pxcb_connection_t; shmseg: xcb_shm_seg_t; size: Cardinal; read_only: Byte): xcb_shm_create_segment_cookie_t; cdecl; external 'xcb-shm' name 'xcb_shm_create_segment';
function xcb_shm_create_segment_unchecked(c: Pxcb_connection_t; shmseg: xcb_shm_seg_t; size: Cardinal; read_only: Byte): xcb_shm_create_segment_cookie_t; cdecl; external 'xcb-shm' name 'xcb_shm_create_segment_unchecked';
function xcb_shm_create_segment_reply(c: Pxcb_connection_t; cookie: xcb_shm_create_segment_cookie_t; e: PPxcb_generic_error_t): Pxcb_shm_create_segment_reply_t; cdecl; external 'xcb-shm' name 'xcb_shm_create_segment_reply';
function xcb_shm_create_segment_reply_fds(c: Pxcb_connection_t; reply: Pxcb_shm_create_segment_reply_t): PInteger; cdecl; external 'xcb-shm' name 'xcb_shm_create_segment_reply_fds';

implementation

end.
