{ Unit Floria.XCB.XFixes — Blaise binding for library 'xcb-xfixes'.
  Generated by blaise-bindgen — DO NOT EDIT.
  Regenerate with:  bindgen --header <header.h> --unit Floria.XCB.XFixes --lib xcb-xfixes }

unit Floria.XCB.XFixes;
{$mode objfpc}{$H+}

interface

uses
  Floria.XCB, Floria.XCB.Render, Floria.XCB.Shape;

type
  Pxcb_xfixes_region_t = ^xcb_xfixes_region_t;
  Pxcb_xfixes_barrier_t = ^xcb_xfixes_barrier_t;
  Pxcb_connection_t = ^xcb_connection_t;
  Pxcb_xfixes_query_version_reply_t = ^xcb_xfixes_query_version_reply_t;
  Pxcb_generic_error_t = ^xcb_generic_error_t;
  PPxcb_generic_error_t = ^Pxcb_generic_error_t;
  PCardinal = ^Cardinal;
  Pxcb_xfixes_get_cursor_image_reply_t = ^xcb_xfixes_get_cursor_image_reply_t;
  Pxcb_xfixes_region_iterator_t = ^xcb_xfixes_region_iterator_t;
  Pxcb_rectangle_t = ^xcb_rectangle_t;
  Pxcb_xfixes_create_region_request_t = ^xcb_xfixes_create_region_request_t;
  Pxcb_xfixes_set_region_request_t = ^xcb_xfixes_set_region_request_t;
  Pxcb_xfixes_fetch_region_reply_t = ^xcb_xfixes_fetch_region_reply_t;
  Pxcb_xfixes_set_cursor_name_request_t = ^xcb_xfixes_set_cursor_name_request_t;
  Pxcb_xfixes_get_cursor_name_reply_t = ^xcb_xfixes_get_cursor_name_reply_t;
  Pxcb_xfixes_get_cursor_image_and_name_reply_t = ^xcb_xfixes_get_cursor_image_and_name_reply_t;
  Pxcb_xfixes_change_cursor_by_name_request_t = ^xcb_xfixes_change_cursor_by_name_request_t;
  Pxcb_xfixes_barrier_iterator_t = ^xcb_xfixes_barrier_iterator_t;
  PWord = ^Word;
  Pxcb_xfixes_create_pointer_barrier_request_t = ^xcb_xfixes_create_pointer_barrier_request_t;
  Pxcb_xfixes_get_client_disconnect_mode_reply_t = ^xcb_xfixes_get_client_disconnect_mode_reply_t;
  xcb_xfixes_query_version_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_xfixes_query_version_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    client_major_version: Cardinal;
    client_minor_version: Cardinal;
  end;
  xcb_xfixes_query_version_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    major_version: Cardinal;
    minor_version: Cardinal;
    pad1: array[0..15] of Byte;
  end;
  xcb_xfixes_save_set_mode_t = Integer;
  xcb_xfixes_save_set_target_t = Integer;
  xcb_xfixes_save_set_mapping_t = Integer;
  xcb_xfixes_change_save_set_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    mode: Byte;
    target: Byte;
    map: Byte;
    pad0: Byte;
    window: xcb_window_t;
  end;
  xcb_xfixes_selection_event_t = Integer;
  xcb_xfixes_selection_event_mask_t = Integer;
  xcb_xfixes_selection_notify_event_t = record
    response_type: Byte;
    subtype: Byte;
    sequence: Word;
    window: xcb_window_t;
    owner: xcb_window_t;
    selection: xcb_atom_t;
    timestamp: xcb_timestamp_t;
    selection_timestamp: xcb_timestamp_t;
    pad0: array[0..7] of Byte;
  end;
  xcb_xfixes_select_selection_input_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    window: xcb_window_t;
    selection: xcb_atom_t;
    event_mask: Cardinal;
  end;
  xcb_xfixes_cursor_notify_t = Integer;
  xcb_xfixes_cursor_notify_mask_t = Integer;
  xcb_xfixes_cursor_notify_event_t = record
    response_type: Byte;
    subtype: Byte;
    sequence: Word;
    window: xcb_window_t;
    cursor_serial: Cardinal;
    timestamp: xcb_timestamp_t;
    name: xcb_atom_t;
    pad0: array[0..11] of Byte;
  end;
  xcb_xfixes_select_cursor_input_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    window: xcb_window_t;
    event_mask: Cardinal;
  end;
  xcb_xfixes_get_cursor_image_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_xfixes_get_cursor_image_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
  end;
  xcb_xfixes_get_cursor_image_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    x: SmallInt;
    y: SmallInt;
    width: Word;
    height: Word;
    xhot: Word;
    yhot: Word;
    cursor_serial: Cardinal;
    pad1: array[0..7] of Byte;
  end;
  xcb_xfixes_region_t = Cardinal;
  xcb_xfixes_region_iterator_t = record
    data: Pxcb_xfixes_region_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_xfixes_bad_region_error_t = record
    response_type: Byte;
    error_code: Byte;
    sequence: Word;
    bad_value: Cardinal;
    minor_opcode: Word;
    major_opcode: Byte;
  end;
  xcb_xfixes_region_enum_t = Integer;
  xcb_xfixes_create_region_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    region: xcb_xfixes_region_t;
  end;
  xcb_xfixes_create_region_from_bitmap_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    region: xcb_xfixes_region_t;
    bitmap: xcb_pixmap_t;
  end;
  xcb_xfixes_create_region_from_window_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    region: xcb_xfixes_region_t;
    window: xcb_window_t;
    kind: xcb_shape_kind_t;
    pad0: array[0..2] of Byte;
  end;
  xcb_xfixes_create_region_from_gc_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    region: xcb_xfixes_region_t;
    gc: xcb_gcontext_t;
  end;
  xcb_xfixes_create_region_from_picture_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    region: xcb_xfixes_region_t;
    picture: xcb_render_picture_t;
  end;
  xcb_xfixes_destroy_region_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    region: xcb_xfixes_region_t;
  end;
  xcb_xfixes_set_region_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    region: xcb_xfixes_region_t;
  end;
  xcb_xfixes_copy_region_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    source: xcb_xfixes_region_t;
    destination: xcb_xfixes_region_t;
  end;
  xcb_xfixes_union_region_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    source1: xcb_xfixes_region_t;
    source2: xcb_xfixes_region_t;
    destination: xcb_xfixes_region_t;
  end;
  xcb_xfixes_intersect_region_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    source1: xcb_xfixes_region_t;
    source2: xcb_xfixes_region_t;
    destination: xcb_xfixes_region_t;
  end;
  xcb_xfixes_subtract_region_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    source1: xcb_xfixes_region_t;
    source2: xcb_xfixes_region_t;
    destination: xcb_xfixes_region_t;
  end;
  xcb_xfixes_invert_region_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    source: xcb_xfixes_region_t;
    bounds: xcb_rectangle_t;
    destination: xcb_xfixes_region_t;
  end;
  xcb_xfixes_translate_region_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    region: xcb_xfixes_region_t;
    dx: SmallInt;
    dy: SmallInt;
  end;
  xcb_xfixes_region_extents_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    source: xcb_xfixes_region_t;
    destination: xcb_xfixes_region_t;
  end;
  xcb_xfixes_fetch_region_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_xfixes_fetch_region_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    region: xcb_xfixes_region_t;
  end;
  xcb_xfixes_fetch_region_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    extents: xcb_rectangle_t;
    pad1: array[0..15] of Byte;
  end;
  xcb_xfixes_set_gc_clip_region_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    gc: xcb_gcontext_t;
    region: xcb_xfixes_region_t;
    x_origin: SmallInt;
    y_origin: SmallInt;
  end;
  xcb_xfixes_set_window_shape_region_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    dest: xcb_window_t;
    dest_kind: xcb_shape_kind_t;
    pad0: array[0..2] of Byte;
    x_offset: SmallInt;
    y_offset: SmallInt;
    region: xcb_xfixes_region_t;
  end;
  xcb_xfixes_set_picture_clip_region_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    picture: xcb_render_picture_t;
    region: xcb_xfixes_region_t;
    x_origin: SmallInt;
    y_origin: SmallInt;
  end;
  xcb_xfixes_set_cursor_name_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    cursor: xcb_cursor_t;
    nbytes: Word;
    pad0: array[0..1] of Byte;
  end;
  xcb_xfixes_get_cursor_name_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_xfixes_get_cursor_name_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    cursor: xcb_cursor_t;
  end;
  xcb_xfixes_get_cursor_name_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    atom: xcb_atom_t;
    nbytes: Word;
    pad1: array[0..17] of Byte;
  end;
  xcb_xfixes_get_cursor_image_and_name_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_xfixes_get_cursor_image_and_name_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
  end;
  xcb_xfixes_get_cursor_image_and_name_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    x: SmallInt;
    y: SmallInt;
    width: Word;
    height: Word;
    xhot: Word;
    yhot: Word;
    cursor_serial: Cardinal;
    cursor_atom: xcb_atom_t;
    nbytes: Word;
    pad1: array[0..1] of Byte;
  end;
  xcb_xfixes_change_cursor_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    source: xcb_cursor_t;
    destination: xcb_cursor_t;
  end;
  xcb_xfixes_change_cursor_by_name_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    src: xcb_cursor_t;
    nbytes: Word;
    pad0: array[0..1] of Byte;
  end;
  xcb_xfixes_expand_region_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    source: xcb_xfixes_region_t;
    destination: xcb_xfixes_region_t;
    left: Word;
    right: Word;
    top: Word;
    bottom: Word;
  end;
  xcb_xfixes_hide_cursor_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    window: xcb_window_t;
  end;
  xcb_xfixes_show_cursor_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    window: xcb_window_t;
  end;
  xcb_xfixes_barrier_t = Cardinal;
  xcb_xfixes_barrier_iterator_t = record
    data: Pxcb_xfixes_barrier_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_xfixes_barrier_directions_t = Integer;
  xcb_xfixes_create_pointer_barrier_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    barrier: xcb_xfixes_barrier_t;
    window: xcb_window_t;
    x1: Word;
    y1: Word;
    x2: Word;
    y2: Word;
    directions: Cardinal;
    pad0: array[0..1] of Byte;
    num_devices: Word;
  end;
  xcb_xfixes_delete_pointer_barrier_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    barrier: xcb_xfixes_barrier_t;
  end;
  xcb_xfixes_client_disconnect_flags_t = Integer;
  xcb_xfixes_set_client_disconnect_mode_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    disconnect_mode: Cardinal;
  end;
  xcb_xfixes_get_client_disconnect_mode_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_xfixes_get_client_disconnect_mode_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
  end;
  xcb_xfixes_get_client_disconnect_mode_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    disconnect_mode: Cardinal;
    pad1: array[0..19] of Byte;
  end;

const
  XCB_XFIXES_SAVE_SET_MODE_INSERT = 0;
  XCB_XFIXES_SAVE_SET_MODE_DELETE = 1;
  XCB_XFIXES_SAVE_SET_TARGET_NEAREST = 0;
  XCB_XFIXES_SAVE_SET_TARGET_ROOT = 1;
  XCB_XFIXES_SAVE_SET_MAPPING_MAP = 0;
  XCB_XFIXES_SAVE_SET_MAPPING_UNMAP = 1;
  XCB_XFIXES_SELECTION_EVENT_SET_SELECTION_OWNER = 0;
  XCB_XFIXES_SELECTION_EVENT_SELECTION_WINDOW_DESTROY = 1;
  XCB_XFIXES_SELECTION_EVENT_SELECTION_CLIENT_CLOSE = 2;
  XCB_XFIXES_SELECTION_EVENT_MASK_SET_SELECTION_OWNER = 1;
  XCB_XFIXES_SELECTION_EVENT_MASK_SELECTION_WINDOW_DESTROY = 2;
  XCB_XFIXES_SELECTION_EVENT_MASK_SELECTION_CLIENT_CLOSE = 4;
  XCB_XFIXES_CURSOR_NOTIFY_DISPLAY_CURSOR = 0;
  XCB_XFIXES_CURSOR_NOTIFY_MASK_DISPLAY_CURSOR = 1;
  XCB_XFIXES_REGION_NONE = 0;
  XCB_XFIXES_BARRIER_DIRECTIONS_POSITIVE_X = 1;
  XCB_XFIXES_BARRIER_DIRECTIONS_POSITIVE_Y = 2;
  XCB_XFIXES_BARRIER_DIRECTIONS_NEGATIVE_X = 4;
  XCB_XFIXES_BARRIER_DIRECTIONS_NEGATIVE_Y = 8;
  XCB_XFIXES_CLIENT_DISCONNECT_FLAGS_DEFAULT = 0;
  XCB_XFIXES_CLIENT_DISCONNECT_FLAGS_TERMINATE = 1;
  XCB_XFIXES_MAJOR_VERSION = 6;
  XCB_XFIXES_MINOR_VERSION = 0;
  XCB_XFIXES_SELECTION_NOTIFY = 0;
  XCB_XFIXES_CURSOR_NOTIFY = 1;
  XCB_XFIXES_BAD_REGION = 0;

function xcb_xfixes_query_version(c: Pxcb_connection_t; client_major_version: Cardinal; client_minor_version: Cardinal): xcb_xfixes_query_version_cookie_t; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_query_version';
function xcb_xfixes_query_version_unchecked(c: Pxcb_connection_t; client_major_version: Cardinal; client_minor_version: Cardinal): xcb_xfixes_query_version_cookie_t; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_query_version_unchecked';
function xcb_xfixes_query_version_reply(c: Pxcb_connection_t; cookie: xcb_xfixes_query_version_cookie_t; e: PPxcb_generic_error_t): Pxcb_xfixes_query_version_reply_t; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_query_version_reply';
{ xcb_xfixes_change_save_set_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_change_save_set: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_select_selection_input_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_select_selection_input: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_select_cursor_input_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_select_cursor_input: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_xfixes_get_cursor_image_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_get_cursor_image_sizeof';
function xcb_xfixes_get_cursor_image(c: Pxcb_connection_t): xcb_xfixes_get_cursor_image_cookie_t; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_get_cursor_image';
function xcb_xfixes_get_cursor_image_unchecked(c: Pxcb_connection_t): xcb_xfixes_get_cursor_image_cookie_t; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_get_cursor_image_unchecked';
function xcb_xfixes_get_cursor_image_cursor_image(R: Pxcb_xfixes_get_cursor_image_reply_t): PCardinal; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_get_cursor_image_cursor_image';
function xcb_xfixes_get_cursor_image_cursor_image_length(R: Pxcb_xfixes_get_cursor_image_reply_t): Integer; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_get_cursor_image_cursor_image_length';
{ xcb_xfixes_get_cursor_image_cursor_image_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_xfixes_get_cursor_image_reply(c: Pxcb_connection_t; cookie: xcb_xfixes_get_cursor_image_cookie_t; e: PPxcb_generic_error_t): Pxcb_xfixes_get_cursor_image_reply_t; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_get_cursor_image_reply';
procedure xcb_xfixes_region_next(i: Pxcb_xfixes_region_iterator_t); cdecl; external 'xcb-xfixes' name 'xcb_xfixes_region_next';
{ xcb_xfixes_region_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_xfixes_create_region_sizeof(_buffer: Pointer; rectangles_len: Cardinal): Integer; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_create_region_sizeof';
{ xcb_xfixes_create_region_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_create_region: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_xfixes_create_region_rectangles(R: Pxcb_xfixes_create_region_request_t): Pxcb_rectangle_t; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_create_region_rectangles';
function xcb_xfixes_create_region_rectangles_length(R: Pxcb_xfixes_create_region_request_t): Integer; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_create_region_rectangles_length';
{ xcb_xfixes_create_region_rectangles_iterator: skipped — return type 'xcb_rectangle_iterator_t' comes from a filtered-out header }
{ xcb_xfixes_create_region_from_bitmap_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_create_region_from_bitmap: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_create_region_from_window_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_create_region_from_window: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_create_region_from_gc_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_create_region_from_gc: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_create_region_from_picture_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_create_region_from_picture: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_destroy_region_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_destroy_region: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_xfixes_set_region_sizeof(_buffer: Pointer; rectangles_len: Cardinal): Integer; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_set_region_sizeof';
{ xcb_xfixes_set_region_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_set_region: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_xfixes_set_region_rectangles(R: Pxcb_xfixes_set_region_request_t): Pxcb_rectangle_t; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_set_region_rectangles';
function xcb_xfixes_set_region_rectangles_length(R: Pxcb_xfixes_set_region_request_t): Integer; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_set_region_rectangles_length';
{ xcb_xfixes_set_region_rectangles_iterator: skipped — return type 'xcb_rectangle_iterator_t' comes from a filtered-out header }
{ xcb_xfixes_copy_region_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_copy_region: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_union_region_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_union_region: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_intersect_region_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_intersect_region: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_subtract_region_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_subtract_region: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_invert_region_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_invert_region: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_translate_region_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_translate_region: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_region_extents_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_region_extents: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_xfixes_fetch_region_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_fetch_region_sizeof';
function xcb_xfixes_fetch_region(c: Pxcb_connection_t; region: xcb_xfixes_region_t): xcb_xfixes_fetch_region_cookie_t; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_fetch_region';
function xcb_xfixes_fetch_region_unchecked(c: Pxcb_connection_t; region: xcb_xfixes_region_t): xcb_xfixes_fetch_region_cookie_t; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_fetch_region_unchecked';
function xcb_xfixes_fetch_region_rectangles(R: Pxcb_xfixes_fetch_region_reply_t): Pxcb_rectangle_t; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_fetch_region_rectangles';
function xcb_xfixes_fetch_region_rectangles_length(R: Pxcb_xfixes_fetch_region_reply_t): Integer; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_fetch_region_rectangles_length';
{ xcb_xfixes_fetch_region_rectangles_iterator: skipped — return type 'xcb_rectangle_iterator_t' comes from a filtered-out header }
function xcb_xfixes_fetch_region_reply(c: Pxcb_connection_t; cookie: xcb_xfixes_fetch_region_cookie_t; e: PPxcb_generic_error_t): Pxcb_xfixes_fetch_region_reply_t; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_fetch_region_reply';
{ xcb_xfixes_set_gc_clip_region_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_set_gc_clip_region: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_set_window_shape_region_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_set_window_shape_region: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_set_picture_clip_region_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_set_picture_clip_region: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_xfixes_set_cursor_name_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_set_cursor_name_sizeof';
{ xcb_xfixes_set_cursor_name_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_set_cursor_name: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_xfixes_set_cursor_name_name(R: Pxcb_xfixes_set_cursor_name_request_t): PChar; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_set_cursor_name_name';
function xcb_xfixes_set_cursor_name_name_length(R: Pxcb_xfixes_set_cursor_name_request_t): Integer; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_set_cursor_name_name_length';
{ xcb_xfixes_set_cursor_name_name_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_xfixes_get_cursor_name_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_get_cursor_name_sizeof';
{ xcb_xfixes_get_cursor_name: skipped — parameter type 'xcb_cursor_t' comes from a filtered-out header }
{ xcb_xfixes_get_cursor_name_unchecked: skipped — parameter type 'xcb_cursor_t' comes from a filtered-out header }
function xcb_xfixes_get_cursor_name_name(R: Pxcb_xfixes_get_cursor_name_reply_t): PChar; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_get_cursor_name_name';
function xcb_xfixes_get_cursor_name_name_length(R: Pxcb_xfixes_get_cursor_name_reply_t): Integer; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_get_cursor_name_name_length';
{ xcb_xfixes_get_cursor_name_name_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_xfixes_get_cursor_name_reply(c: Pxcb_connection_t; cookie: xcb_xfixes_get_cursor_name_cookie_t; e: PPxcb_generic_error_t): Pxcb_xfixes_get_cursor_name_reply_t; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_get_cursor_name_reply';
function xcb_xfixes_get_cursor_image_and_name_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_get_cursor_image_and_name_sizeof';
function xcb_xfixes_get_cursor_image_and_name(c: Pxcb_connection_t): xcb_xfixes_get_cursor_image_and_name_cookie_t; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_get_cursor_image_and_name';
function xcb_xfixes_get_cursor_image_and_name_unchecked(c: Pxcb_connection_t): xcb_xfixes_get_cursor_image_and_name_cookie_t; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_get_cursor_image_and_name_unchecked';
function xcb_xfixes_get_cursor_image_and_name_cursor_image(R: Pxcb_xfixes_get_cursor_image_and_name_reply_t): PCardinal; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_get_cursor_image_and_name_cursor_image';
function xcb_xfixes_get_cursor_image_and_name_cursor_image_length(R: Pxcb_xfixes_get_cursor_image_and_name_reply_t): Integer; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_get_cursor_image_and_name_cursor_image_length';
{ xcb_xfixes_get_cursor_image_and_name_cursor_image_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_xfixes_get_cursor_image_and_name_name(R: Pxcb_xfixes_get_cursor_image_and_name_reply_t): PChar; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_get_cursor_image_and_name_name';
function xcb_xfixes_get_cursor_image_and_name_name_length(R: Pxcb_xfixes_get_cursor_image_and_name_reply_t): Integer; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_get_cursor_image_and_name_name_length';
{ xcb_xfixes_get_cursor_image_and_name_name_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_xfixes_get_cursor_image_and_name_reply(c: Pxcb_connection_t; cookie: xcb_xfixes_get_cursor_image_and_name_cookie_t; e: PPxcb_generic_error_t): Pxcb_xfixes_get_cursor_image_and_name_reply_t; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_get_cursor_image_and_name_reply';
{ xcb_xfixes_change_cursor_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_change_cursor: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_xfixes_change_cursor_by_name_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_change_cursor_by_name_sizeof';
{ xcb_xfixes_change_cursor_by_name_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_change_cursor_by_name: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_xfixes_change_cursor_by_name_name(R: Pxcb_xfixes_change_cursor_by_name_request_t): PChar; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_change_cursor_by_name_name';
function xcb_xfixes_change_cursor_by_name_name_length(R: Pxcb_xfixes_change_cursor_by_name_request_t): Integer; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_change_cursor_by_name_name_length';
{ xcb_xfixes_change_cursor_by_name_name_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
{ xcb_xfixes_expand_region_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_expand_region: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_hide_cursor_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_hide_cursor: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_show_cursor_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_show_cursor: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
procedure xcb_xfixes_barrier_next(i: Pxcb_xfixes_barrier_iterator_t); cdecl; external 'xcb-xfixes' name 'xcb_xfixes_barrier_next';
{ xcb_xfixes_barrier_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_xfixes_create_pointer_barrier_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_create_pointer_barrier_sizeof';
{ xcb_xfixes_create_pointer_barrier_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_create_pointer_barrier: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_xfixes_create_pointer_barrier_devices(R: Pxcb_xfixes_create_pointer_barrier_request_t): PWord; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_create_pointer_barrier_devices';
function xcb_xfixes_create_pointer_barrier_devices_length(R: Pxcb_xfixes_create_pointer_barrier_request_t): Integer; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_create_pointer_barrier_devices_length';
{ xcb_xfixes_create_pointer_barrier_devices_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
{ xcb_xfixes_delete_pointer_barrier_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_delete_pointer_barrier: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_set_client_disconnect_mode_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_xfixes_set_client_disconnect_mode: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_xfixes_get_client_disconnect_mode(c: Pxcb_connection_t): xcb_xfixes_get_client_disconnect_mode_cookie_t; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_get_client_disconnect_mode';
function xcb_xfixes_get_client_disconnect_mode_unchecked(c: Pxcb_connection_t): xcb_xfixes_get_client_disconnect_mode_cookie_t; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_get_client_disconnect_mode_unchecked';
function xcb_xfixes_get_client_disconnect_mode_reply(c: Pxcb_connection_t; cookie: xcb_xfixes_get_client_disconnect_mode_cookie_t; e: PPxcb_generic_error_t): Pxcb_xfixes_get_client_disconnect_mode_reply_t; cdecl; external 'xcb-xfixes' name 'xcb_xfixes_get_client_disconnect_mode_reply';

implementation

end.
