{ Unit Floria.XCB.ICCCM — Blaise binding for library 'xcb-icccm'.
  Generated by blaise-bindgen — DO NOT EDIT.
  Regenerate with:  bindgen --header <header.h> --unit Floria.XCB.ICCCM --lib xcb-icccm }

unit Floria.XCB.ICCCM;
{$mode objfpc}{$H+}

interface

uses
  Floria.XCB;

type
  Pxcb_icccm_get_text_property_reply_t = ^xcb_icccm_get_text_property_reply_t;
  PPxcb_generic_error_t = ^Pxcb_generic_error_t;
  Pxcb_icccm_get_wm_colormap_windows_reply_t = ^xcb_icccm_get_wm_colormap_windows_reply_t;
  Pxcb_icccm_get_wm_class_reply_t = ^xcb_icccm_get_wm_class_reply_t;
  Pxcb_size_hints_t = ^xcb_size_hints_t;
  Pxcb_icccm_wm_hints_t = ^xcb_icccm_wm_hints_t;
  Pxcb_icccm_get_wm_protocols_reply_t = ^xcb_icccm_get_wm_protocols_reply_t;
  xcb_icccm_get_text_property_reply_t = record
    _reply: Pxcb_get_property_reply_t;
    encoding: xcb_atom_t;
    name_len: Cardinal;
    name: PChar;
    format: Byte;
  end;
  xcb_icccm_get_wm_colormap_windows_reply_t = record
    windows_len: Cardinal;
    windows: Pxcb_window_t;
    _reply: Pxcb_get_property_reply_t;
  end;
  xcb_icccm_get_wm_class_reply_t = record
    instance_name: PChar;
    class_name: PChar;
    _reply: Pxcb_get_property_reply_t;
  end;
  xcb_icccm_size_hints_flags_t = Integer;
  xcb_size_hints_t = record
    flags: Cardinal;
    x: Integer;
    y: Integer;
    width: Integer;
    height: Integer;
    min_width: Integer;
    min_height: Integer;
    max_width: Integer;
    max_height: Integer;
    width_inc: Integer;
    height_inc: Integer;
    min_aspect_num: Integer;
    min_aspect_den: Integer;
    max_aspect_num: Integer;
    max_aspect_den: Integer;
    base_width: Integer;
    base_height: Integer;
    win_gravity: Cardinal;
  end;
  xcb_icccm_wm_hints_t = record
    flags: Integer;
    input: Cardinal;
    initial_state: Integer;
    icon_pixmap: xcb_pixmap_t;
    icon_window: xcb_window_t;
    icon_x: Integer;
    icon_y: Integer;
    icon_mask: xcb_pixmap_t;
    window_group: xcb_window_t;
  end;
  xcb_icccm_wm_state_t = Integer;
  xcb_icccm_wm_t = Integer;
  xcb_icccm_get_wm_protocols_reply_t = record
    atoms_len: Cardinal;
    atoms: Pxcb_atom_t;
    _reply: Pxcb_get_property_reply_t;
  end;

const
  XCB_ICCCM_SIZE_HINT_US_POSITION = 1;
  XCB_ICCCM_SIZE_HINT_US_SIZE = 2;
  XCB_ICCCM_SIZE_HINT_P_POSITION = 4;
  XCB_ICCCM_SIZE_HINT_P_SIZE = 8;
  XCB_ICCCM_SIZE_HINT_P_MIN_SIZE = 16;
  XCB_ICCCM_SIZE_HINT_P_MAX_SIZE = 32;
  XCB_ICCCM_SIZE_HINT_P_RESIZE_INC = 64;
  XCB_ICCCM_SIZE_HINT_P_ASPECT = 128;
  XCB_ICCCM_SIZE_HINT_BASE_SIZE = 256;
  XCB_ICCCM_SIZE_HINT_P_WIN_GRAVITY = 512;
  XCB_ICCCM_WM_STATE_WITHDRAWN = 0;
  XCB_ICCCM_WM_STATE_NORMAL = 1;
  XCB_ICCCM_WM_STATE_ICONIC = 3;
  XCB_ICCCM_WM_HINT_INPUT = 1;
  XCB_ICCCM_WM_HINT_STATE = 2;
  XCB_ICCCM_WM_HINT_ICON_PIXMAP = 4;
  XCB_ICCCM_WM_HINT_ICON_WINDOW = 8;
  XCB_ICCCM_WM_HINT_ICON_POSITION = 16;
  XCB_ICCCM_WM_HINT_ICON_MASK = 32;
  XCB_ICCCM_WM_HINT_WINDOW_GROUP = 64;
  XCB_ICCCM_WM_HINT_X_URGENCY = 256;
  XCB_ICCCM_NUM_WM_SIZE_HINTS_ELEMENTS = 18;
  XCB_ICCCM_NUM_WM_HINTS_ELEMENTS = 9;

{ xcb_icccm_get_text_property: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_text_property_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_text_property_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
procedure xcb_icccm_get_text_property_reply_wipe(prop: Pxcb_icccm_get_text_property_reply_t); cdecl; external 'xcb-icccm' name 'xcb_icccm_get_text_property_reply_wipe';
{ xcb_icccm_set_wm_name_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_icccm_set_wm_name: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_name: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_name_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_name_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_icccm_set_wm_icon_name_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_icccm_set_wm_icon_name: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_icon_name: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_icon_name_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_icon_name_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_icccm_set_wm_colormap_windows_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_icccm_set_wm_colormap_windows: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_colormap_windows: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_colormap_windows_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
function xcb_icccm_get_wm_colormap_windows_from_reply(reply: Pxcb_get_property_reply_t; colormap_windows: Pxcb_icccm_get_wm_colormap_windows_reply_t): Byte; cdecl; external 'xcb-icccm' name 'xcb_icccm_get_wm_colormap_windows_from_reply';
{ xcb_icccm_get_wm_colormap_windows_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
procedure xcb_icccm_get_wm_colormap_windows_reply_wipe(windows: Pxcb_icccm_get_wm_colormap_windows_reply_t); cdecl; external 'xcb-icccm' name 'xcb_icccm_get_wm_colormap_windows_reply_wipe';
{ xcb_icccm_set_wm_client_machine_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_icccm_set_wm_client_machine: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_client_machine: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_client_machine_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_client_machine_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_icccm_set_wm_class_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_icccm_set_wm_class: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_class: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_class_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
function xcb_icccm_get_wm_class_from_reply(prop: Pxcb_icccm_get_wm_class_reply_t; reply: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-icccm' name 'xcb_icccm_get_wm_class_from_reply';
{ xcb_icccm_get_wm_class_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
procedure xcb_icccm_get_wm_class_reply_wipe(prop: Pxcb_icccm_get_wm_class_reply_t); cdecl; external 'xcb-icccm' name 'xcb_icccm_get_wm_class_reply_wipe';
{ xcb_icccm_set_wm_transient_for_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_icccm_set_wm_transient_for: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_transient_for: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_transient_for_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
function xcb_icccm_get_wm_transient_for_from_reply(prop: Pxcb_window_t; reply: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-icccm' name 'xcb_icccm_get_wm_transient_for_from_reply';
{ xcb_icccm_get_wm_transient_for_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
procedure xcb_icccm_size_hints_set_position(hints: Pxcb_size_hints_t; user_specified: Integer; x: Integer; y: Integer); cdecl; external 'xcb-icccm' name 'xcb_icccm_size_hints_set_position';
procedure xcb_icccm_size_hints_set_size(hints: Pxcb_size_hints_t; user_specified: Integer; width: Integer; height: Integer); cdecl; external 'xcb-icccm' name 'xcb_icccm_size_hints_set_size';
procedure xcb_icccm_size_hints_set_min_size(hints: Pxcb_size_hints_t; min_width: Integer; min_height: Integer); cdecl; external 'xcb-icccm' name 'xcb_icccm_size_hints_set_min_size';
procedure xcb_icccm_size_hints_set_max_size(hints: Pxcb_size_hints_t; max_width: Integer; max_height: Integer); cdecl; external 'xcb-icccm' name 'xcb_icccm_size_hints_set_max_size';
procedure xcb_icccm_size_hints_set_resize_inc(hints: Pxcb_size_hints_t; width_inc: Integer; height_inc: Integer); cdecl; external 'xcb-icccm' name 'xcb_icccm_size_hints_set_resize_inc';
procedure xcb_icccm_size_hints_set_aspect(hints: Pxcb_size_hints_t; min_aspect_num: Integer; min_aspect_den: Integer; max_aspect_num: Integer; max_aspect_den: Integer); cdecl; external 'xcb-icccm' name 'xcb_icccm_size_hints_set_aspect';
procedure xcb_icccm_size_hints_set_base_size(hints: Pxcb_size_hints_t; base_width: Integer; base_height: Integer); cdecl; external 'xcb-icccm' name 'xcb_icccm_size_hints_set_base_size';
{ xcb_icccm_size_hints_set_win_gravity: skipped — parameter type 'xcb_gravity_t' comes from a filtered-out header }
{ xcb_icccm_set_wm_size_hints_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_icccm_set_wm_size_hints: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_size_hints: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_size_hints_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_size_hints_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_icccm_set_wm_normal_hints_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_icccm_set_wm_normal_hints: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_normal_hints: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_normal_hints_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
function xcb_icccm_get_wm_size_hints_from_reply(hints: Pxcb_size_hints_t; reply: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-icccm' name 'xcb_icccm_get_wm_size_hints_from_reply';
{ xcb_icccm_get_wm_normal_hints_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
function xcb_icccm_wm_hints_get_urgency(hints: Pxcb_icccm_wm_hints_t): Cardinal; cdecl; external 'xcb-icccm' name 'xcb_icccm_wm_hints_get_urgency';
procedure xcb_icccm_wm_hints_set_input(hints: Pxcb_icccm_wm_hints_t; input: Byte); cdecl; external 'xcb-icccm' name 'xcb_icccm_wm_hints_set_input';
procedure xcb_icccm_wm_hints_set_iconic(hints: Pxcb_icccm_wm_hints_t); cdecl; external 'xcb-icccm' name 'xcb_icccm_wm_hints_set_iconic';
procedure xcb_icccm_wm_hints_set_normal(hints: Pxcb_icccm_wm_hints_t); cdecl; external 'xcb-icccm' name 'xcb_icccm_wm_hints_set_normal';
procedure xcb_icccm_wm_hints_set_withdrawn(hints: Pxcb_icccm_wm_hints_t); cdecl; external 'xcb-icccm' name 'xcb_icccm_wm_hints_set_withdrawn';
procedure xcb_icccm_wm_hints_set_none(hints: Pxcb_icccm_wm_hints_t); cdecl; external 'xcb-icccm' name 'xcb_icccm_wm_hints_set_none';
{ xcb_icccm_wm_hints_set_icon_pixmap: skipped — parameter type 'xcb_pixmap_t' comes from a filtered-out header }
{ xcb_icccm_wm_hints_set_icon_mask: skipped — parameter type 'xcb_pixmap_t' comes from a filtered-out header }
{ xcb_icccm_wm_hints_set_icon_window: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
{ xcb_icccm_wm_hints_set_window_group: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
procedure xcb_icccm_wm_hints_set_urgency(hints: Pxcb_icccm_wm_hints_t); cdecl; external 'xcb-icccm' name 'xcb_icccm_wm_hints_set_urgency';
{ xcb_icccm_set_wm_hints_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_icccm_set_wm_hints: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_hints: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_hints_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
function xcb_icccm_get_wm_hints_from_reply(hints: Pxcb_icccm_wm_hints_t; reply: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-icccm' name 'xcb_icccm_get_wm_hints_from_reply';
{ xcb_icccm_get_wm_hints_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_icccm_set_wm_protocols_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_icccm_set_wm_protocols: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_protocols: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_icccm_get_wm_protocols_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
function xcb_icccm_get_wm_protocols_from_reply(reply: Pxcb_get_property_reply_t; protocols: Pxcb_icccm_get_wm_protocols_reply_t): Byte; cdecl; external 'xcb-icccm' name 'xcb_icccm_get_wm_protocols_from_reply';
{ xcb_icccm_get_wm_protocols_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
procedure xcb_icccm_get_wm_protocols_reply_wipe(protocols: Pxcb_icccm_get_wm_protocols_reply_t); cdecl; external 'xcb-icccm' name 'xcb_icccm_get_wm_protocols_reply_wipe';

implementation

end.
