{ Unit Floria.XCB.Render — Blaise binding for library 'xcb-render'.
  Generated by blaise-bindgen — DO NOT EDIT.
  Regenerate with:  bindgen --header <header.h> --unit Floria.XCB.Render --lib xcb-render }

unit Floria.XCB.Render;
{$mode objfpc}{$H+}

interface

uses
  Floria.XCB;

type
  Pxcb_render_glyph_t = ^xcb_render_glyph_t;
  Pxcb_render_glyphset_t = ^xcb_render_glyphset_t;
  Pxcb_render_picture_t = ^xcb_render_picture_t;
  Pxcb_render_pictformat_t = ^xcb_render_pictformat_t;
  Pxcb_render_fixed_t = ^xcb_render_fixed_t;
  Pxcb_render_directformat_t = ^xcb_render_directformat_t;
  Pxcb_render_pictforminfo_t = ^xcb_render_pictforminfo_t;
  Pxcb_render_pictvisual_t = ^xcb_render_pictvisual_t;
  Pxcb_render_pictdepth_t = ^xcb_render_pictdepth_t;
  Pxcb_render_pictscreen_t = ^xcb_render_pictscreen_t;
  Pxcb_render_indexvalue_t = ^xcb_render_indexvalue_t;
  Pxcb_render_color_t = ^xcb_render_color_t;
  Pxcb_render_pointfix_t = ^xcb_render_pointfix_t;
  Pxcb_render_linefix_t = ^xcb_render_linefix_t;
  Pxcb_render_triangle_t = ^xcb_render_triangle_t;
  Pxcb_render_trapezoid_t = ^xcb_render_trapezoid_t;
  Pxcb_render_glyphinfo_t = ^xcb_render_glyphinfo_t;
  Pxcb_render_transform_t = ^xcb_render_transform_t;
  Pxcb_render_animcursorelt_t = ^xcb_render_animcursorelt_t;
  Pxcb_render_spanfix_t = ^xcb_render_spanfix_t;
  Pxcb_render_trap_t = ^xcb_render_trap_t;
  Pxcb_render_glyph_iterator_t = ^xcb_render_glyph_iterator_t;
  Pxcb_render_glyphset_iterator_t = ^xcb_render_glyphset_iterator_t;
  Pxcb_render_picture_iterator_t = ^xcb_render_picture_iterator_t;
  Pxcb_render_pictformat_iterator_t = ^xcb_render_pictformat_iterator_t;
  Pxcb_render_fixed_iterator_t = ^xcb_render_fixed_iterator_t;
  Pxcb_render_directformat_iterator_t = ^xcb_render_directformat_iterator_t;
  Pxcb_render_pictforminfo_iterator_t = ^xcb_render_pictforminfo_iterator_t;
  Pxcb_render_pictvisual_iterator_t = ^xcb_render_pictvisual_iterator_t;
  Pxcb_render_pictdepth_iterator_t = ^xcb_render_pictdepth_iterator_t;
  Pxcb_render_pictscreen_iterator_t = ^xcb_render_pictscreen_iterator_t;
  Pxcb_render_indexvalue_iterator_t = ^xcb_render_indexvalue_iterator_t;
  Pxcb_render_color_iterator_t = ^xcb_render_color_iterator_t;
  Pxcb_render_pointfix_iterator_t = ^xcb_render_pointfix_iterator_t;
  Pxcb_render_linefix_iterator_t = ^xcb_render_linefix_iterator_t;
  Pxcb_render_triangle_iterator_t = ^xcb_render_triangle_iterator_t;
  Pxcb_render_trapezoid_iterator_t = ^xcb_render_trapezoid_iterator_t;
  Pxcb_render_glyphinfo_iterator_t = ^xcb_render_glyphinfo_iterator_t;
  Pxcb_connection_t = ^xcb_connection_t;
  Pxcb_render_query_version_reply_t = ^xcb_render_query_version_reply_t;
  Pxcb_generic_error_t = ^xcb_generic_error_t;
  PPxcb_generic_error_t = ^Pxcb_generic_error_t;
  Pxcb_render_query_pict_formats_reply_t = ^xcb_render_query_pict_formats_reply_t;
  PCardinal = ^Cardinal;
  Pxcb_render_query_pict_index_values_reply_t = ^xcb_render_query_pict_index_values_reply_t;
  PPointer = ^Pointer;
  Pxcb_render_create_picture_value_list_t = ^xcb_render_create_picture_value_list_t;
  Pxcb_render_create_picture_request_t = ^xcb_render_create_picture_request_t;
  Pxcb_render_change_picture_value_list_t = ^xcb_render_change_picture_value_list_t;
  Pxcb_render_change_picture_request_t = ^xcb_render_change_picture_request_t;
  Pxcb_rectangle_t = ^xcb_rectangle_t;
  Pxcb_render_set_picture_clip_rectangles_request_t = ^xcb_render_set_picture_clip_rectangles_request_t;
  Pxcb_render_trapezoids_request_t = ^xcb_render_trapezoids_request_t;
  Pxcb_render_triangles_request_t = ^xcb_render_triangles_request_t;
  Pxcb_render_tri_strip_request_t = ^xcb_render_tri_strip_request_t;
  Pxcb_render_tri_fan_request_t = ^xcb_render_tri_fan_request_t;
  PByte = ^Byte;
  Pxcb_render_add_glyphs_request_t = ^xcb_render_add_glyphs_request_t;
  Pxcb_render_free_glyphs_request_t = ^xcb_render_free_glyphs_request_t;
  Pxcb_render_composite_glyphs_8_request_t = ^xcb_render_composite_glyphs_8_request_t;
  Pxcb_render_composite_glyphs_16_request_t = ^xcb_render_composite_glyphs_16_request_t;
  Pxcb_render_composite_glyphs_32_request_t = ^xcb_render_composite_glyphs_32_request_t;
  Pxcb_render_fill_rectangles_request_t = ^xcb_render_fill_rectangles_request_t;
  Pxcb_render_transform_iterator_t = ^xcb_render_transform_iterator_t;
  PWord = ^Word;
  Pxcb_render_query_filters_reply_t = ^xcb_render_query_filters_reply_t;
  Pxcb_render_set_picture_filter_request_t = ^xcb_render_set_picture_filter_request_t;
  Pxcb_render_animcursorelt_iterator_t = ^xcb_render_animcursorelt_iterator_t;
  Pxcb_render_create_anim_cursor_request_t = ^xcb_render_create_anim_cursor_request_t;
  Pxcb_render_spanfix_iterator_t = ^xcb_render_spanfix_iterator_t;
  Pxcb_render_trap_iterator_t = ^xcb_render_trap_iterator_t;
  Pxcb_render_add_traps_request_t = ^xcb_render_add_traps_request_t;
  Pxcb_render_create_linear_gradient_request_t = ^xcb_render_create_linear_gradient_request_t;
  Pxcb_render_create_radial_gradient_request_t = ^xcb_render_create_radial_gradient_request_t;
  Pxcb_render_create_conical_gradient_request_t = ^xcb_render_create_conical_gradient_request_t;
  xcb_render_pict_type_t = Integer;
  xcb_render_picture_enum_t = Integer;
  xcb_render_pict_op_t = Integer;
  xcb_render_poly_edge_t = Integer;
  xcb_render_poly_mode_t = Integer;
  xcb_render_cp_t = Integer;
  xcb_render_sub_pixel_t = Integer;
  xcb_render_repeat_t = Integer;
  xcb_render_glyph_t = Cardinal;
  xcb_render_glyph_iterator_t = record
    data: Pxcb_render_glyph_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_render_glyphset_t = Cardinal;
  xcb_render_glyphset_iterator_t = record
    data: Pxcb_render_glyphset_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_render_picture_t = Cardinal;
  xcb_render_picture_iterator_t = record
    data: Pxcb_render_picture_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_render_pictformat_t = Cardinal;
  xcb_render_pictformat_iterator_t = record
    data: Pxcb_render_pictformat_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_render_fixed_t = Integer;
  xcb_render_fixed_iterator_t = record
    data: Pxcb_render_fixed_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_render_pict_format_error_t = record
    response_type: Byte;
    error_code: Byte;
    sequence: Word;
    bad_value: Cardinal;
    minor_opcode: Word;
    major_opcode: Byte;
  end;
  xcb_render_picture_error_t = record
    response_type: Byte;
    error_code: Byte;
    sequence: Word;
    bad_value: Cardinal;
    minor_opcode: Word;
    major_opcode: Byte;
  end;
  xcb_render_pict_op_error_t = record
    response_type: Byte;
    error_code: Byte;
    sequence: Word;
    bad_value: Cardinal;
    minor_opcode: Word;
    major_opcode: Byte;
  end;
  xcb_render_glyph_set_error_t = record
    response_type: Byte;
    error_code: Byte;
    sequence: Word;
    bad_value: Cardinal;
    minor_opcode: Word;
    major_opcode: Byte;
  end;
  xcb_render_glyph_error_t = record
    response_type: Byte;
    error_code: Byte;
    sequence: Word;
    bad_value: Cardinal;
    minor_opcode: Word;
    major_opcode: Byte;
  end;
  xcb_render_directformat_t = record
    red_shift: Word;
    red_mask: Word;
    green_shift: Word;
    green_mask: Word;
    blue_shift: Word;
    blue_mask: Word;
    alpha_shift: Word;
    alpha_mask: Word;
  end;
  xcb_render_directformat_iterator_t = record
    data: Pxcb_render_directformat_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_render_pictforminfo_t = record
    id: xcb_render_pictformat_t;
    type_: Byte;
    depth: Byte;
    pad0: array[0..1] of Byte;
    direct: xcb_render_directformat_t;
    colormap: xcb_colormap_t;
  end;
  xcb_render_pictforminfo_iterator_t = record
    data: Pxcb_render_pictforminfo_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_render_pictvisual_t = record
    visual: xcb_visualid_t;
    format: xcb_render_pictformat_t;
  end;
  xcb_render_pictvisual_iterator_t = record
    data: Pxcb_render_pictvisual_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_render_pictdepth_t = record
    depth: Byte;
    pad0: Byte;
    num_visuals: Word;
    pad1: array[0..3] of Byte;
  end;
  xcb_render_pictdepth_iterator_t = record
    data: Pxcb_render_pictdepth_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_render_pictscreen_t = record
    num_depths: Cardinal;
    fallback: xcb_render_pictformat_t;
  end;
  xcb_render_pictscreen_iterator_t = record
    data: Pxcb_render_pictscreen_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_render_indexvalue_t = record
    pixel: Cardinal;
    red: Word;
    green: Word;
    blue: Word;
    alpha: Word;
  end;
  xcb_render_indexvalue_iterator_t = record
    data: Pxcb_render_indexvalue_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_render_color_t = record
    red: Word;
    green: Word;
    blue: Word;
    alpha: Word;
  end;
  xcb_render_color_iterator_t = record
    data: Pxcb_render_color_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_render_pointfix_t = record
    x: xcb_render_fixed_t;
    y: xcb_render_fixed_t;
  end;
  xcb_render_pointfix_iterator_t = record
    data: Pxcb_render_pointfix_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_render_linefix_t = record
    p1: xcb_render_pointfix_t;
    p2: xcb_render_pointfix_t;
  end;
  xcb_render_linefix_iterator_t = record
    data: Pxcb_render_linefix_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_render_triangle_t = record
    p1: xcb_render_pointfix_t;
    p2: xcb_render_pointfix_t;
    p3: xcb_render_pointfix_t;
  end;
  xcb_render_triangle_iterator_t = record
    data: Pxcb_render_triangle_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_render_trapezoid_t = record
    top: xcb_render_fixed_t;
    bottom: xcb_render_fixed_t;
    left: xcb_render_linefix_t;
    right: xcb_render_linefix_t;
  end;
  xcb_render_trapezoid_iterator_t = record
    data: Pxcb_render_trapezoid_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_render_glyphinfo_t = record
    width: Word;
    height: Word;
    x: SmallInt;
    y: SmallInt;
    x_off: SmallInt;
    y_off: SmallInt;
  end;
  xcb_render_glyphinfo_iterator_t = record
    data: Pxcb_render_glyphinfo_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_render_query_version_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_render_query_version_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    client_major_version: Cardinal;
    client_minor_version: Cardinal;
  end;
  xcb_render_query_version_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    major_version: Cardinal;
    minor_version: Cardinal;
    pad1: array[0..15] of Byte;
  end;
  xcb_render_query_pict_formats_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_render_query_pict_formats_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
  end;
  xcb_render_query_pict_formats_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    num_formats: Cardinal;
    num_screens: Cardinal;
    num_depths: Cardinal;
    num_visuals: Cardinal;
    num_subpixel: Cardinal;
    pad1: array[0..3] of Byte;
  end;
  xcb_render_query_pict_index_values_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_render_query_pict_index_values_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    format: xcb_render_pictformat_t;
  end;
  xcb_render_query_pict_index_values_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    num_values: Cardinal;
    pad1: array[0..19] of Byte;
  end;
  xcb_render_create_picture_value_list_t = record
    repeat_: Cardinal;
    alphamap: xcb_render_picture_t;
    alphaxorigin: Integer;
    alphayorigin: Integer;
    clipxorigin: Integer;
    clipyorigin: Integer;
    clipmask: xcb_pixmap_t;
    graphicsexposure: Cardinal;
    subwindowmode: Cardinal;
    polyedge: Cardinal;
    polymode: Cardinal;
    dither: xcb_atom_t;
    componentalpha: Cardinal;
  end;
  xcb_render_create_picture_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    pid: xcb_render_picture_t;
    drawable: xcb_drawable_t;
    format: xcb_render_pictformat_t;
    value_mask: Cardinal;
  end;
  xcb_render_change_picture_value_list_t = record
    repeat_: Cardinal;
    alphamap: xcb_render_picture_t;
    alphaxorigin: Integer;
    alphayorigin: Integer;
    clipxorigin: Integer;
    clipyorigin: Integer;
    clipmask: xcb_pixmap_t;
    graphicsexposure: Cardinal;
    subwindowmode: Cardinal;
    polyedge: Cardinal;
    polymode: Cardinal;
    dither: xcb_atom_t;
    componentalpha: Cardinal;
  end;
  xcb_render_change_picture_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    picture: xcb_render_picture_t;
    value_mask: Cardinal;
  end;
  xcb_render_set_picture_clip_rectangles_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    picture: xcb_render_picture_t;
    clip_x_origin: SmallInt;
    clip_y_origin: SmallInt;
  end;
  xcb_render_free_picture_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    picture: xcb_render_picture_t;
  end;
  xcb_render_composite_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    op: Byte;
    pad0: array[0..2] of Byte;
    src: xcb_render_picture_t;
    mask: xcb_render_picture_t;
    dst: xcb_render_picture_t;
    src_x: SmallInt;
    src_y: SmallInt;
    mask_x: SmallInt;
    mask_y: SmallInt;
    dst_x: SmallInt;
    dst_y: SmallInt;
    width: Word;
    height: Word;
  end;
  xcb_render_trapezoids_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    op: Byte;
    pad0: array[0..2] of Byte;
    src: xcb_render_picture_t;
    dst: xcb_render_picture_t;
    mask_format: xcb_render_pictformat_t;
    src_x: SmallInt;
    src_y: SmallInt;
  end;
  xcb_render_triangles_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    op: Byte;
    pad0: array[0..2] of Byte;
    src: xcb_render_picture_t;
    dst: xcb_render_picture_t;
    mask_format: xcb_render_pictformat_t;
    src_x: SmallInt;
    src_y: SmallInt;
  end;
  xcb_render_tri_strip_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    op: Byte;
    pad0: array[0..2] of Byte;
    src: xcb_render_picture_t;
    dst: xcb_render_picture_t;
    mask_format: xcb_render_pictformat_t;
    src_x: SmallInt;
    src_y: SmallInt;
  end;
  xcb_render_tri_fan_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    op: Byte;
    pad0: array[0..2] of Byte;
    src: xcb_render_picture_t;
    dst: xcb_render_picture_t;
    mask_format: xcb_render_pictformat_t;
    src_x: SmallInt;
    src_y: SmallInt;
  end;
  xcb_render_create_glyph_set_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    gsid: xcb_render_glyphset_t;
    format: xcb_render_pictformat_t;
  end;
  xcb_render_reference_glyph_set_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    gsid: xcb_render_glyphset_t;
    existing: xcb_render_glyphset_t;
  end;
  xcb_render_free_glyph_set_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    glyphset: xcb_render_glyphset_t;
  end;
  xcb_render_add_glyphs_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    glyphset: xcb_render_glyphset_t;
    glyphs_len: Cardinal;
  end;
  xcb_render_free_glyphs_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    glyphset: xcb_render_glyphset_t;
  end;
  xcb_render_composite_glyphs_8_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    op: Byte;
    pad0: array[0..2] of Byte;
    src: xcb_render_picture_t;
    dst: xcb_render_picture_t;
    mask_format: xcb_render_pictformat_t;
    glyphset: xcb_render_glyphset_t;
    src_x: SmallInt;
    src_y: SmallInt;
  end;
  xcb_render_composite_glyphs_16_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    op: Byte;
    pad0: array[0..2] of Byte;
    src: xcb_render_picture_t;
    dst: xcb_render_picture_t;
    mask_format: xcb_render_pictformat_t;
    glyphset: xcb_render_glyphset_t;
    src_x: SmallInt;
    src_y: SmallInt;
  end;
  xcb_render_composite_glyphs_32_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    op: Byte;
    pad0: array[0..2] of Byte;
    src: xcb_render_picture_t;
    dst: xcb_render_picture_t;
    mask_format: xcb_render_pictformat_t;
    glyphset: xcb_render_glyphset_t;
    src_x: SmallInt;
    src_y: SmallInt;
  end;
  xcb_render_fill_rectangles_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    op: Byte;
    pad0: array[0..2] of Byte;
    dst: xcb_render_picture_t;
    color: xcb_render_color_t;
  end;
  xcb_render_create_cursor_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    cid: xcb_cursor_t;
    source: xcb_render_picture_t;
    x: Word;
    y: Word;
  end;
  xcb_render_transform_t = record
    matrix11: xcb_render_fixed_t;
    matrix12: xcb_render_fixed_t;
    matrix13: xcb_render_fixed_t;
    matrix21: xcb_render_fixed_t;
    matrix22: xcb_render_fixed_t;
    matrix23: xcb_render_fixed_t;
    matrix31: xcb_render_fixed_t;
    matrix32: xcb_render_fixed_t;
    matrix33: xcb_render_fixed_t;
  end;
  xcb_render_transform_iterator_t = record
    data: Pxcb_render_transform_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_render_set_picture_transform_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    picture: xcb_render_picture_t;
    transform: xcb_render_transform_t;
  end;
  xcb_render_query_filters_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_render_query_filters_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    drawable: xcb_drawable_t;
  end;
  xcb_render_query_filters_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    num_aliases: Cardinal;
    num_filters: Cardinal;
    pad1: array[0..15] of Byte;
  end;
  xcb_render_set_picture_filter_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    picture: xcb_render_picture_t;
    filter_len: Word;
    pad0: array[0..1] of Byte;
  end;
  xcb_render_animcursorelt_t = record
    cursor: xcb_cursor_t;
    delay: Cardinal;
  end;
  xcb_render_animcursorelt_iterator_t = record
    data: Pxcb_render_animcursorelt_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_render_create_anim_cursor_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    cid: xcb_cursor_t;
  end;
  xcb_render_spanfix_t = record
    l: xcb_render_fixed_t;
    r: xcb_render_fixed_t;
    y: xcb_render_fixed_t;
  end;
  xcb_render_spanfix_iterator_t = record
    data: Pxcb_render_spanfix_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_render_trap_t = record
    top: xcb_render_spanfix_t;
    bot: xcb_render_spanfix_t;
  end;
  xcb_render_trap_iterator_t = record
    data: Pxcb_render_trap_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_render_add_traps_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    picture: xcb_render_picture_t;
    x_off: SmallInt;
    y_off: SmallInt;
  end;
  xcb_render_create_solid_fill_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    picture: xcb_render_picture_t;
    color: xcb_render_color_t;
  end;
  xcb_render_create_linear_gradient_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    picture: xcb_render_picture_t;
    p1: xcb_render_pointfix_t;
    p2: xcb_render_pointfix_t;
    num_stops: Cardinal;
  end;
  xcb_render_create_radial_gradient_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    picture: xcb_render_picture_t;
    inner: xcb_render_pointfix_t;
    outer: xcb_render_pointfix_t;
    inner_radius: xcb_render_fixed_t;
    outer_radius: xcb_render_fixed_t;
    num_stops: Cardinal;
  end;
  xcb_render_create_conical_gradient_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    picture: xcb_render_picture_t;
    center: xcb_render_pointfix_t;
    angle: xcb_render_fixed_t;
    num_stops: Cardinal;
  end;

const
  XCB_RENDER_PICT_TYPE_INDEXED = 0;
  XCB_RENDER_PICT_TYPE_DIRECT = 1;
  XCB_RENDER_PICTURE_NONE = 0;
  XCB_RENDER_PICT_OP_CLEAR = 0;
  XCB_RENDER_PICT_OP_SRC = 1;
  XCB_RENDER_PICT_OP_DST = 2;
  XCB_RENDER_PICT_OP_OVER = 3;
  XCB_RENDER_PICT_OP_OVER_REVERSE = 4;
  XCB_RENDER_PICT_OP_IN = 5;
  XCB_RENDER_PICT_OP_IN_REVERSE = 6;
  XCB_RENDER_PICT_OP_OUT = 7;
  XCB_RENDER_PICT_OP_OUT_REVERSE = 8;
  XCB_RENDER_PICT_OP_ATOP = 9;
  XCB_RENDER_PICT_OP_ATOP_REVERSE = 10;
  XCB_RENDER_PICT_OP_XOR = 11;
  XCB_RENDER_PICT_OP_ADD = 12;
  XCB_RENDER_PICT_OP_SATURATE = 13;
  XCB_RENDER_PICT_OP_DISJOINT_CLEAR = 16;
  XCB_RENDER_PICT_OP_DISJOINT_SRC = 17;
  XCB_RENDER_PICT_OP_DISJOINT_DST = 18;
  XCB_RENDER_PICT_OP_DISJOINT_OVER = 19;
  XCB_RENDER_PICT_OP_DISJOINT_OVER_REVERSE = 20;
  XCB_RENDER_PICT_OP_DISJOINT_IN = 21;
  XCB_RENDER_PICT_OP_DISJOINT_IN_REVERSE = 22;
  XCB_RENDER_PICT_OP_DISJOINT_OUT = 23;
  XCB_RENDER_PICT_OP_DISJOINT_OUT_REVERSE = 24;
  XCB_RENDER_PICT_OP_DISJOINT_ATOP = 25;
  XCB_RENDER_PICT_OP_DISJOINT_ATOP_REVERSE = 26;
  XCB_RENDER_PICT_OP_DISJOINT_XOR = 27;
  XCB_RENDER_PICT_OP_CONJOINT_CLEAR = 32;
  XCB_RENDER_PICT_OP_CONJOINT_SRC = 33;
  XCB_RENDER_PICT_OP_CONJOINT_DST = 34;
  XCB_RENDER_PICT_OP_CONJOINT_OVER = 35;
  XCB_RENDER_PICT_OP_CONJOINT_OVER_REVERSE = 36;
  XCB_RENDER_PICT_OP_CONJOINT_IN = 37;
  XCB_RENDER_PICT_OP_CONJOINT_IN_REVERSE = 38;
  XCB_RENDER_PICT_OP_CONJOINT_OUT = 39;
  XCB_RENDER_PICT_OP_CONJOINT_OUT_REVERSE = 40;
  XCB_RENDER_PICT_OP_CONJOINT_ATOP = 41;
  XCB_RENDER_PICT_OP_CONJOINT_ATOP_REVERSE = 42;
  XCB_RENDER_PICT_OP_CONJOINT_XOR = 43;
  XCB_RENDER_PICT_OP_MULTIPLY = 48;
  XCB_RENDER_PICT_OP_SCREEN = 49;
  XCB_RENDER_PICT_OP_OVERLAY = 50;
  XCB_RENDER_PICT_OP_DARKEN = 51;
  XCB_RENDER_PICT_OP_LIGHTEN = 52;
  XCB_RENDER_PICT_OP_COLOR_DODGE = 53;
  XCB_RENDER_PICT_OP_COLOR_BURN = 54;
  XCB_RENDER_PICT_OP_HARD_LIGHT = 55;
  XCB_RENDER_PICT_OP_SOFT_LIGHT = 56;
  XCB_RENDER_PICT_OP_DIFFERENCE = 57;
  XCB_RENDER_PICT_OP_EXCLUSION = 58;
  XCB_RENDER_PICT_OP_HSL_HUE = 59;
  XCB_RENDER_PICT_OP_HSL_SATURATION = 60;
  XCB_RENDER_PICT_OP_HSL_COLOR = 61;
  XCB_RENDER_PICT_OP_HSL_LUMINOSITY = 62;
  XCB_RENDER_POLY_EDGE_SHARP = 0;
  XCB_RENDER_POLY_EDGE_SMOOTH = 1;
  XCB_RENDER_POLY_MODE_PRECISE = 0;
  XCB_RENDER_POLY_MODE_IMPRECISE = 1;
  XCB_RENDER_CP_REPEAT = 1;
  XCB_RENDER_CP_ALPHA_MAP = 2;
  XCB_RENDER_CP_ALPHA_X_ORIGIN = 4;
  XCB_RENDER_CP_ALPHA_Y_ORIGIN = 8;
  XCB_RENDER_CP_CLIP_X_ORIGIN = 16;
  XCB_RENDER_CP_CLIP_Y_ORIGIN = 32;
  XCB_RENDER_CP_CLIP_MASK = 64;
  XCB_RENDER_CP_GRAPHICS_EXPOSURE = 128;
  XCB_RENDER_CP_SUBWINDOW_MODE = 256;
  XCB_RENDER_CP_POLY_EDGE = 512;
  XCB_RENDER_CP_POLY_MODE = 1024;
  XCB_RENDER_CP_DITHER = 2048;
  XCB_RENDER_CP_COMPONENT_ALPHA = 4096;
  XCB_RENDER_SUB_PIXEL_UNKNOWN = 0;
  XCB_RENDER_SUB_PIXEL_HORIZONTAL_RGB = 1;
  XCB_RENDER_SUB_PIXEL_HORIZONTAL_BGR = 2;
  XCB_RENDER_SUB_PIXEL_VERTICAL_RGB = 3;
  XCB_RENDER_SUB_PIXEL_VERTICAL_BGR = 4;
  XCB_RENDER_SUB_PIXEL_NONE = 5;
  XCB_RENDER_REPEAT_NONE = 0;
  XCB_RENDER_REPEAT_NORMAL = 1;
  XCB_RENDER_REPEAT_PAD = 2;
  XCB_RENDER_REPEAT_REFLECT = 3;
  XCB_RENDER_MAJOR_VERSION = 0;
  XCB_RENDER_MINOR_VERSION = 11;
  XCB_RENDER_PICT_FORMAT = 0;
  XCB_RENDER_PICTURE = 1;
  XCB_RENDER_PICT_OP = 2;
  XCB_RENDER_GLYPH_SET = 3;
  XCB_RENDER_GLYPH = 4;

procedure xcb_render_glyph_next(i: Pxcb_render_glyph_iterator_t); cdecl; external 'xcb-render' name 'xcb_render_glyph_next';
{ xcb_render_glyph_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_render_glyphset_next(i: Pxcb_render_glyphset_iterator_t); cdecl; external 'xcb-render' name 'xcb_render_glyphset_next';
{ xcb_render_glyphset_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_render_picture_next(i: Pxcb_render_picture_iterator_t); cdecl; external 'xcb-render' name 'xcb_render_picture_next';
{ xcb_render_picture_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_render_pictformat_next(i: Pxcb_render_pictformat_iterator_t); cdecl; external 'xcb-render' name 'xcb_render_pictformat_next';
{ xcb_render_pictformat_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_render_fixed_next(i: Pxcb_render_fixed_iterator_t); cdecl; external 'xcb-render' name 'xcb_render_fixed_next';
{ xcb_render_fixed_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_render_directformat_next(i: Pxcb_render_directformat_iterator_t); cdecl; external 'xcb-render' name 'xcb_render_directformat_next';
{ xcb_render_directformat_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_render_pictforminfo_next(i: Pxcb_render_pictforminfo_iterator_t); cdecl; external 'xcb-render' name 'xcb_render_pictforminfo_next';
{ xcb_render_pictforminfo_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_render_pictvisual_next(i: Pxcb_render_pictvisual_iterator_t); cdecl; external 'xcb-render' name 'xcb_render_pictvisual_next';
{ xcb_render_pictvisual_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_render_pictdepth_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-render' name 'xcb_render_pictdepth_sizeof';
function xcb_render_pictdepth_visuals(R: Pxcb_render_pictdepth_t): Pxcb_render_pictvisual_t; cdecl; external 'xcb-render' name 'xcb_render_pictdepth_visuals';
function xcb_render_pictdepth_visuals_length(R: Pxcb_render_pictdepth_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_pictdepth_visuals_length';
function xcb_render_pictdepth_visuals_iterator(R: Pxcb_render_pictdepth_t): xcb_render_pictvisual_iterator_t; cdecl; external 'xcb-render' name 'xcb_render_pictdepth_visuals_iterator';
procedure xcb_render_pictdepth_next(i: Pxcb_render_pictdepth_iterator_t); cdecl; external 'xcb-render' name 'xcb_render_pictdepth_next';
{ xcb_render_pictdepth_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_render_pictscreen_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-render' name 'xcb_render_pictscreen_sizeof';
function xcb_render_pictscreen_depths_length(R: Pxcb_render_pictscreen_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_pictscreen_depths_length';
function xcb_render_pictscreen_depths_iterator(R: Pxcb_render_pictscreen_t): xcb_render_pictdepth_iterator_t; cdecl; external 'xcb-render' name 'xcb_render_pictscreen_depths_iterator';
procedure xcb_render_pictscreen_next(i: Pxcb_render_pictscreen_iterator_t); cdecl; external 'xcb-render' name 'xcb_render_pictscreen_next';
{ xcb_render_pictscreen_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_render_indexvalue_next(i: Pxcb_render_indexvalue_iterator_t); cdecl; external 'xcb-render' name 'xcb_render_indexvalue_next';
{ xcb_render_indexvalue_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_render_color_next(i: Pxcb_render_color_iterator_t); cdecl; external 'xcb-render' name 'xcb_render_color_next';
{ xcb_render_color_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_render_pointfix_next(i: Pxcb_render_pointfix_iterator_t); cdecl; external 'xcb-render' name 'xcb_render_pointfix_next';
{ xcb_render_pointfix_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_render_linefix_next(i: Pxcb_render_linefix_iterator_t); cdecl; external 'xcb-render' name 'xcb_render_linefix_next';
{ xcb_render_linefix_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_render_triangle_next(i: Pxcb_render_triangle_iterator_t); cdecl; external 'xcb-render' name 'xcb_render_triangle_next';
{ xcb_render_triangle_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_render_trapezoid_next(i: Pxcb_render_trapezoid_iterator_t); cdecl; external 'xcb-render' name 'xcb_render_trapezoid_next';
{ xcb_render_trapezoid_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_render_glyphinfo_next(i: Pxcb_render_glyphinfo_iterator_t); cdecl; external 'xcb-render' name 'xcb_render_glyphinfo_next';
{ xcb_render_glyphinfo_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_render_query_version(c: Pxcb_connection_t; client_major_version: Cardinal; client_minor_version: Cardinal): xcb_render_query_version_cookie_t; cdecl; external 'xcb-render' name 'xcb_render_query_version';
function xcb_render_query_version_unchecked(c: Pxcb_connection_t; client_major_version: Cardinal; client_minor_version: Cardinal): xcb_render_query_version_cookie_t; cdecl; external 'xcb-render' name 'xcb_render_query_version_unchecked';
function xcb_render_query_version_reply(c: Pxcb_connection_t; cookie: xcb_render_query_version_cookie_t; e: PPxcb_generic_error_t): Pxcb_render_query_version_reply_t; cdecl; external 'xcb-render' name 'xcb_render_query_version_reply';
function xcb_render_query_pict_formats_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-render' name 'xcb_render_query_pict_formats_sizeof';
function xcb_render_query_pict_formats(c: Pxcb_connection_t): xcb_render_query_pict_formats_cookie_t; cdecl; external 'xcb-render' name 'xcb_render_query_pict_formats';
function xcb_render_query_pict_formats_unchecked(c: Pxcb_connection_t): xcb_render_query_pict_formats_cookie_t; cdecl; external 'xcb-render' name 'xcb_render_query_pict_formats_unchecked';
function xcb_render_query_pict_formats_formats(R: Pxcb_render_query_pict_formats_reply_t): Pxcb_render_pictforminfo_t; cdecl; external 'xcb-render' name 'xcb_render_query_pict_formats_formats';
function xcb_render_query_pict_formats_formats_length(R: Pxcb_render_query_pict_formats_reply_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_query_pict_formats_formats_length';
function xcb_render_query_pict_formats_formats_iterator(R: Pxcb_render_query_pict_formats_reply_t): xcb_render_pictforminfo_iterator_t; cdecl; external 'xcb-render' name 'xcb_render_query_pict_formats_formats_iterator';
function xcb_render_query_pict_formats_screens_length(R: Pxcb_render_query_pict_formats_reply_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_query_pict_formats_screens_length';
function xcb_render_query_pict_formats_screens_iterator(R: Pxcb_render_query_pict_formats_reply_t): xcb_render_pictscreen_iterator_t; cdecl; external 'xcb-render' name 'xcb_render_query_pict_formats_screens_iterator';
function xcb_render_query_pict_formats_subpixels(R: Pxcb_render_query_pict_formats_reply_t): PCardinal; cdecl; external 'xcb-render' name 'xcb_render_query_pict_formats_subpixels';
function xcb_render_query_pict_formats_subpixels_length(R: Pxcb_render_query_pict_formats_reply_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_query_pict_formats_subpixels_length';
{ xcb_render_query_pict_formats_subpixels_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_render_query_pict_formats_reply(c: Pxcb_connection_t; cookie: xcb_render_query_pict_formats_cookie_t; e: PPxcb_generic_error_t): Pxcb_render_query_pict_formats_reply_t; cdecl; external 'xcb-render' name 'xcb_render_query_pict_formats_reply';
function xcb_render_query_pict_index_values_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-render' name 'xcb_render_query_pict_index_values_sizeof';
function xcb_render_query_pict_index_values(c: Pxcb_connection_t; format: xcb_render_pictformat_t): xcb_render_query_pict_index_values_cookie_t; cdecl; external 'xcb-render' name 'xcb_render_query_pict_index_values';
function xcb_render_query_pict_index_values_unchecked(c: Pxcb_connection_t; format: xcb_render_pictformat_t): xcb_render_query_pict_index_values_cookie_t; cdecl; external 'xcb-render' name 'xcb_render_query_pict_index_values_unchecked';
function xcb_render_query_pict_index_values_values(R: Pxcb_render_query_pict_index_values_reply_t): Pxcb_render_indexvalue_t; cdecl; external 'xcb-render' name 'xcb_render_query_pict_index_values_values';
function xcb_render_query_pict_index_values_values_length(R: Pxcb_render_query_pict_index_values_reply_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_query_pict_index_values_values_length';
function xcb_render_query_pict_index_values_values_iterator(R: Pxcb_render_query_pict_index_values_reply_t): xcb_render_indexvalue_iterator_t; cdecl; external 'xcb-render' name 'xcb_render_query_pict_index_values_values_iterator';
function xcb_render_query_pict_index_values_reply(c: Pxcb_connection_t; cookie: xcb_render_query_pict_index_values_cookie_t; e: PPxcb_generic_error_t): Pxcb_render_query_pict_index_values_reply_t; cdecl; external 'xcb-render' name 'xcb_render_query_pict_index_values_reply';
function xcb_render_create_picture_value_list_serialize(_buffer: PPointer; value_mask: Cardinal; _aux: Pxcb_render_create_picture_value_list_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_create_picture_value_list_serialize';
function xcb_render_create_picture_value_list_unpack(_buffer: Pointer; value_mask: Cardinal; _aux: Pxcb_render_create_picture_value_list_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_create_picture_value_list_unpack';
function xcb_render_create_picture_value_list_sizeof(_buffer: Pointer; value_mask: Cardinal): Integer; cdecl; external 'xcb-render' name 'xcb_render_create_picture_value_list_sizeof';
function xcb_render_create_picture_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-render' name 'xcb_render_create_picture_sizeof';
{ xcb_render_create_picture_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_create_picture: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_create_picture_aux_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_create_picture_aux: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_create_picture_value_list(R: Pxcb_render_create_picture_request_t): Pointer; cdecl; external 'xcb-render' name 'xcb_render_create_picture_value_list';
function xcb_render_change_picture_value_list_serialize(_buffer: PPointer; value_mask: Cardinal; _aux: Pxcb_render_change_picture_value_list_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_change_picture_value_list_serialize';
function xcb_render_change_picture_value_list_unpack(_buffer: Pointer; value_mask: Cardinal; _aux: Pxcb_render_change_picture_value_list_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_change_picture_value_list_unpack';
function xcb_render_change_picture_value_list_sizeof(_buffer: Pointer; value_mask: Cardinal): Integer; cdecl; external 'xcb-render' name 'xcb_render_change_picture_value_list_sizeof';
function xcb_render_change_picture_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-render' name 'xcb_render_change_picture_sizeof';
{ xcb_render_change_picture_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_change_picture: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_change_picture_aux_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_change_picture_aux: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_change_picture_value_list(R: Pxcb_render_change_picture_request_t): Pointer; cdecl; external 'xcb-render' name 'xcb_render_change_picture_value_list';
function xcb_render_set_picture_clip_rectangles_sizeof(_buffer: Pointer; rectangles_len: Cardinal): Integer; cdecl; external 'xcb-render' name 'xcb_render_set_picture_clip_rectangles_sizeof';
{ xcb_render_set_picture_clip_rectangles_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_set_picture_clip_rectangles: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_set_picture_clip_rectangles_rectangles(R: Pxcb_render_set_picture_clip_rectangles_request_t): Pxcb_rectangle_t; cdecl; external 'xcb-render' name 'xcb_render_set_picture_clip_rectangles_rectangles';
function xcb_render_set_picture_clip_rectangles_rectangles_length(R: Pxcb_render_set_picture_clip_rectangles_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_set_picture_clip_rectangles_rectangles_length';
{ xcb_render_set_picture_clip_rectangles_rectangles_iterator: skipped — return type 'xcb_rectangle_iterator_t' comes from a filtered-out header }
{ xcb_render_free_picture_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_free_picture: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_composite_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_composite: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_trapezoids_sizeof(_buffer: Pointer; traps_len: Cardinal): Integer; cdecl; external 'xcb-render' name 'xcb_render_trapezoids_sizeof';
{ xcb_render_trapezoids_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_trapezoids: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_trapezoids_traps(R: Pxcb_render_trapezoids_request_t): Pxcb_render_trapezoid_t; cdecl; external 'xcb-render' name 'xcb_render_trapezoids_traps';
function xcb_render_trapezoids_traps_length(R: Pxcb_render_trapezoids_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_trapezoids_traps_length';
function xcb_render_trapezoids_traps_iterator(R: Pxcb_render_trapezoids_request_t): xcb_render_trapezoid_iterator_t; cdecl; external 'xcb-render' name 'xcb_render_trapezoids_traps_iterator';
function xcb_render_triangles_sizeof(_buffer: Pointer; triangles_len: Cardinal): Integer; cdecl; external 'xcb-render' name 'xcb_render_triangles_sizeof';
{ xcb_render_triangles_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_triangles: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_triangles_triangles(R: Pxcb_render_triangles_request_t): Pxcb_render_triangle_t; cdecl; external 'xcb-render' name 'xcb_render_triangles_triangles';
function xcb_render_triangles_triangles_length(R: Pxcb_render_triangles_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_triangles_triangles_length';
function xcb_render_triangles_triangles_iterator(R: Pxcb_render_triangles_request_t): xcb_render_triangle_iterator_t; cdecl; external 'xcb-render' name 'xcb_render_triangles_triangles_iterator';
function xcb_render_tri_strip_sizeof(_buffer: Pointer; points_len: Cardinal): Integer; cdecl; external 'xcb-render' name 'xcb_render_tri_strip_sizeof';
{ xcb_render_tri_strip_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_tri_strip: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_tri_strip_points(R: Pxcb_render_tri_strip_request_t): Pxcb_render_pointfix_t; cdecl; external 'xcb-render' name 'xcb_render_tri_strip_points';
function xcb_render_tri_strip_points_length(R: Pxcb_render_tri_strip_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_tri_strip_points_length';
function xcb_render_tri_strip_points_iterator(R: Pxcb_render_tri_strip_request_t): xcb_render_pointfix_iterator_t; cdecl; external 'xcb-render' name 'xcb_render_tri_strip_points_iterator';
function xcb_render_tri_fan_sizeof(_buffer: Pointer; points_len: Cardinal): Integer; cdecl; external 'xcb-render' name 'xcb_render_tri_fan_sizeof';
{ xcb_render_tri_fan_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_tri_fan: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_tri_fan_points(R: Pxcb_render_tri_fan_request_t): Pxcb_render_pointfix_t; cdecl; external 'xcb-render' name 'xcb_render_tri_fan_points';
function xcb_render_tri_fan_points_length(R: Pxcb_render_tri_fan_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_tri_fan_points_length';
function xcb_render_tri_fan_points_iterator(R: Pxcb_render_tri_fan_request_t): xcb_render_pointfix_iterator_t; cdecl; external 'xcb-render' name 'xcb_render_tri_fan_points_iterator';
{ xcb_render_create_glyph_set_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_create_glyph_set: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_reference_glyph_set_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_reference_glyph_set: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_free_glyph_set_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_free_glyph_set: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_add_glyphs_sizeof(_buffer: Pointer; data_len: Cardinal): Integer; cdecl; external 'xcb-render' name 'xcb_render_add_glyphs_sizeof';
{ xcb_render_add_glyphs_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_add_glyphs: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_add_glyphs_glyphids(R: Pxcb_render_add_glyphs_request_t): PCardinal; cdecl; external 'xcb-render' name 'xcb_render_add_glyphs_glyphids';
function xcb_render_add_glyphs_glyphids_length(R: Pxcb_render_add_glyphs_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_add_glyphs_glyphids_length';
{ xcb_render_add_glyphs_glyphids_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_render_add_glyphs_glyphs(R: Pxcb_render_add_glyphs_request_t): Pxcb_render_glyphinfo_t; cdecl; external 'xcb-render' name 'xcb_render_add_glyphs_glyphs';
function xcb_render_add_glyphs_glyphs_length(R: Pxcb_render_add_glyphs_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_add_glyphs_glyphs_length';
function xcb_render_add_glyphs_glyphs_iterator(R: Pxcb_render_add_glyphs_request_t): xcb_render_glyphinfo_iterator_t; cdecl; external 'xcb-render' name 'xcb_render_add_glyphs_glyphs_iterator';
function xcb_render_add_glyphs_data(R: Pxcb_render_add_glyphs_request_t): PByte; cdecl; external 'xcb-render' name 'xcb_render_add_glyphs_data';
function xcb_render_add_glyphs_data_length(R: Pxcb_render_add_glyphs_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_add_glyphs_data_length';
{ xcb_render_add_glyphs_data_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_render_free_glyphs_sizeof(_buffer: Pointer; glyphs_len: Cardinal): Integer; cdecl; external 'xcb-render' name 'xcb_render_free_glyphs_sizeof';
{ xcb_render_free_glyphs_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_free_glyphs: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_free_glyphs_glyphs(R: Pxcb_render_free_glyphs_request_t): Pxcb_render_glyph_t; cdecl; external 'xcb-render' name 'xcb_render_free_glyphs_glyphs';
function xcb_render_free_glyphs_glyphs_length(R: Pxcb_render_free_glyphs_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_free_glyphs_glyphs_length';
{ xcb_render_free_glyphs_glyphs_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_render_composite_glyphs_8_sizeof(_buffer: Pointer; glyphcmds_len: Cardinal): Integer; cdecl; external 'xcb-render' name 'xcb_render_composite_glyphs_8_sizeof';
{ xcb_render_composite_glyphs_8_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_composite_glyphs_8: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_composite_glyphs_8_glyphcmds(R: Pxcb_render_composite_glyphs_8_request_t): PByte; cdecl; external 'xcb-render' name 'xcb_render_composite_glyphs_8_glyphcmds';
function xcb_render_composite_glyphs_8_glyphcmds_length(R: Pxcb_render_composite_glyphs_8_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_composite_glyphs_8_glyphcmds_length';
{ xcb_render_composite_glyphs_8_glyphcmds_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_render_composite_glyphs_16_sizeof(_buffer: Pointer; glyphcmds_len: Cardinal): Integer; cdecl; external 'xcb-render' name 'xcb_render_composite_glyphs_16_sizeof';
{ xcb_render_composite_glyphs_16_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_composite_glyphs_16: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_composite_glyphs_16_glyphcmds(R: Pxcb_render_composite_glyphs_16_request_t): PByte; cdecl; external 'xcb-render' name 'xcb_render_composite_glyphs_16_glyphcmds';
function xcb_render_composite_glyphs_16_glyphcmds_length(R: Pxcb_render_composite_glyphs_16_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_composite_glyphs_16_glyphcmds_length';
{ xcb_render_composite_glyphs_16_glyphcmds_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_render_composite_glyphs_32_sizeof(_buffer: Pointer; glyphcmds_len: Cardinal): Integer; cdecl; external 'xcb-render' name 'xcb_render_composite_glyphs_32_sizeof';
{ xcb_render_composite_glyphs_32_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_composite_glyphs_32: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_composite_glyphs_32_glyphcmds(R: Pxcb_render_composite_glyphs_32_request_t): PByte; cdecl; external 'xcb-render' name 'xcb_render_composite_glyphs_32_glyphcmds';
function xcb_render_composite_glyphs_32_glyphcmds_length(R: Pxcb_render_composite_glyphs_32_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_composite_glyphs_32_glyphcmds_length';
{ xcb_render_composite_glyphs_32_glyphcmds_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_render_fill_rectangles_sizeof(_buffer: Pointer; rects_len: Cardinal): Integer; cdecl; external 'xcb-render' name 'xcb_render_fill_rectangles_sizeof';
{ xcb_render_fill_rectangles_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_fill_rectangles: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_fill_rectangles_rects(R: Pxcb_render_fill_rectangles_request_t): Pxcb_rectangle_t; cdecl; external 'xcb-render' name 'xcb_render_fill_rectangles_rects';
function xcb_render_fill_rectangles_rects_length(R: Pxcb_render_fill_rectangles_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_fill_rectangles_rects_length';
{ xcb_render_fill_rectangles_rects_iterator: skipped — return type 'xcb_rectangle_iterator_t' comes from a filtered-out header }
{ xcb_render_create_cursor_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_create_cursor: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
procedure xcb_render_transform_next(i: Pxcb_render_transform_iterator_t); cdecl; external 'xcb-render' name 'xcb_render_transform_next';
{ xcb_render_transform_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
{ xcb_render_set_picture_transform_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_set_picture_transform: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_query_filters_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-render' name 'xcb_render_query_filters_sizeof';
{ xcb_render_query_filters: skipped — parameter type 'xcb_drawable_t' comes from a filtered-out header }
{ xcb_render_query_filters_unchecked: skipped — parameter type 'xcb_drawable_t' comes from a filtered-out header }
function xcb_render_query_filters_aliases(R: Pxcb_render_query_filters_reply_t): PWord; cdecl; external 'xcb-render' name 'xcb_render_query_filters_aliases';
function xcb_render_query_filters_aliases_length(R: Pxcb_render_query_filters_reply_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_query_filters_aliases_length';
{ xcb_render_query_filters_aliases_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_render_query_filters_filters_length(R: Pxcb_render_query_filters_reply_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_query_filters_filters_length';
{ xcb_render_query_filters_filters_iterator: skipped — return type 'xcb_str_iterator_t' comes from a filtered-out header }
function xcb_render_query_filters_reply(c: Pxcb_connection_t; cookie: xcb_render_query_filters_cookie_t; e: PPxcb_generic_error_t): Pxcb_render_query_filters_reply_t; cdecl; external 'xcb-render' name 'xcb_render_query_filters_reply';
function xcb_render_set_picture_filter_sizeof(_buffer: Pointer; values_len: Cardinal): Integer; cdecl; external 'xcb-render' name 'xcb_render_set_picture_filter_sizeof';
{ xcb_render_set_picture_filter_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_set_picture_filter: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_set_picture_filter_filter(R: Pxcb_render_set_picture_filter_request_t): PChar; cdecl; external 'xcb-render' name 'xcb_render_set_picture_filter_filter';
function xcb_render_set_picture_filter_filter_length(R: Pxcb_render_set_picture_filter_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_set_picture_filter_filter_length';
{ xcb_render_set_picture_filter_filter_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_render_set_picture_filter_values(R: Pxcb_render_set_picture_filter_request_t): Pxcb_render_fixed_t; cdecl; external 'xcb-render' name 'xcb_render_set_picture_filter_values';
function xcb_render_set_picture_filter_values_length(R: Pxcb_render_set_picture_filter_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_set_picture_filter_values_length';
{ xcb_render_set_picture_filter_values_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_render_animcursorelt_next(i: Pxcb_render_animcursorelt_iterator_t); cdecl; external 'xcb-render' name 'xcb_render_animcursorelt_next';
{ xcb_render_animcursorelt_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_render_create_anim_cursor_sizeof(_buffer: Pointer; cursors_len: Cardinal): Integer; cdecl; external 'xcb-render' name 'xcb_render_create_anim_cursor_sizeof';
{ xcb_render_create_anim_cursor_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_create_anim_cursor: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_create_anim_cursor_cursors(R: Pxcb_render_create_anim_cursor_request_t): Pxcb_render_animcursorelt_t; cdecl; external 'xcb-render' name 'xcb_render_create_anim_cursor_cursors';
function xcb_render_create_anim_cursor_cursors_length(R: Pxcb_render_create_anim_cursor_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_create_anim_cursor_cursors_length';
function xcb_render_create_anim_cursor_cursors_iterator(R: Pxcb_render_create_anim_cursor_request_t): xcb_render_animcursorelt_iterator_t; cdecl; external 'xcb-render' name 'xcb_render_create_anim_cursor_cursors_iterator';
procedure xcb_render_spanfix_next(i: Pxcb_render_spanfix_iterator_t); cdecl; external 'xcb-render' name 'xcb_render_spanfix_next';
{ xcb_render_spanfix_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_render_trap_next(i: Pxcb_render_trap_iterator_t); cdecl; external 'xcb-render' name 'xcb_render_trap_next';
{ xcb_render_trap_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_render_add_traps_sizeof(_buffer: Pointer; traps_len: Cardinal): Integer; cdecl; external 'xcb-render' name 'xcb_render_add_traps_sizeof';
{ xcb_render_add_traps_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_add_traps: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_add_traps_traps(R: Pxcb_render_add_traps_request_t): Pxcb_render_trap_t; cdecl; external 'xcb-render' name 'xcb_render_add_traps_traps';
function xcb_render_add_traps_traps_length(R: Pxcb_render_add_traps_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_add_traps_traps_length';
function xcb_render_add_traps_traps_iterator(R: Pxcb_render_add_traps_request_t): xcb_render_trap_iterator_t; cdecl; external 'xcb-render' name 'xcb_render_add_traps_traps_iterator';
{ xcb_render_create_solid_fill_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_create_solid_fill: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_create_linear_gradient_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-render' name 'xcb_render_create_linear_gradient_sizeof';
{ xcb_render_create_linear_gradient_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_create_linear_gradient: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_create_linear_gradient_stops(R: Pxcb_render_create_linear_gradient_request_t): Pxcb_render_fixed_t; cdecl; external 'xcb-render' name 'xcb_render_create_linear_gradient_stops';
function xcb_render_create_linear_gradient_stops_length(R: Pxcb_render_create_linear_gradient_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_create_linear_gradient_stops_length';
{ xcb_render_create_linear_gradient_stops_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_render_create_linear_gradient_colors(R: Pxcb_render_create_linear_gradient_request_t): Pxcb_render_color_t; cdecl; external 'xcb-render' name 'xcb_render_create_linear_gradient_colors';
function xcb_render_create_linear_gradient_colors_length(R: Pxcb_render_create_linear_gradient_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_create_linear_gradient_colors_length';
function xcb_render_create_linear_gradient_colors_iterator(R: Pxcb_render_create_linear_gradient_request_t): xcb_render_color_iterator_t; cdecl; external 'xcb-render' name 'xcb_render_create_linear_gradient_colors_iterator';
function xcb_render_create_radial_gradient_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-render' name 'xcb_render_create_radial_gradient_sizeof';
{ xcb_render_create_radial_gradient_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_create_radial_gradient: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_create_radial_gradient_stops(R: Pxcb_render_create_radial_gradient_request_t): Pxcb_render_fixed_t; cdecl; external 'xcb-render' name 'xcb_render_create_radial_gradient_stops';
function xcb_render_create_radial_gradient_stops_length(R: Pxcb_render_create_radial_gradient_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_create_radial_gradient_stops_length';
{ xcb_render_create_radial_gradient_stops_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_render_create_radial_gradient_colors(R: Pxcb_render_create_radial_gradient_request_t): Pxcb_render_color_t; cdecl; external 'xcb-render' name 'xcb_render_create_radial_gradient_colors';
function xcb_render_create_radial_gradient_colors_length(R: Pxcb_render_create_radial_gradient_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_create_radial_gradient_colors_length';
function xcb_render_create_radial_gradient_colors_iterator(R: Pxcb_render_create_radial_gradient_request_t): xcb_render_color_iterator_t; cdecl; external 'xcb-render' name 'xcb_render_create_radial_gradient_colors_iterator';
function xcb_render_create_conical_gradient_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-render' name 'xcb_render_create_conical_gradient_sizeof';
{ xcb_render_create_conical_gradient_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_render_create_conical_gradient: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_render_create_conical_gradient_stops(R: Pxcb_render_create_conical_gradient_request_t): Pxcb_render_fixed_t; cdecl; external 'xcb-render' name 'xcb_render_create_conical_gradient_stops';
function xcb_render_create_conical_gradient_stops_length(R: Pxcb_render_create_conical_gradient_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_create_conical_gradient_stops_length';
{ xcb_render_create_conical_gradient_stops_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_render_create_conical_gradient_colors(R: Pxcb_render_create_conical_gradient_request_t): Pxcb_render_color_t; cdecl; external 'xcb-render' name 'xcb_render_create_conical_gradient_colors';
function xcb_render_create_conical_gradient_colors_length(R: Pxcb_render_create_conical_gradient_request_t): Integer; cdecl; external 'xcb-render' name 'xcb_render_create_conical_gradient_colors_length';
function xcb_render_create_conical_gradient_colors_iterator(R: Pxcb_render_create_conical_gradient_request_t): xcb_render_color_iterator_t; cdecl; external 'xcb-render' name 'xcb_render_create_conical_gradient_colors_iterator';

implementation

end.
