{ Unit Floria.XCB.RandR — Blaise binding for library 'xcb-randr'.
  Generated by blaise-bindgen — DO NOT EDIT.
  Regenerate with:  bindgen --header <header.h> --unit Floria.XCB.RandR --lib xcb-randr }

unit Floria.XCB.RandR;
{$mode objfpc}{$H+}

interface

uses
  Floria.XCB, Floria.XCB.Render;

type
  Pxcb_randr_mode_t = ^xcb_randr_mode_t;
  Pxcb_randr_crtc_t = ^xcb_randr_crtc_t;
  Pxcb_randr_output_t = ^xcb_randr_output_t;
  Pxcb_randr_provider_t = ^xcb_randr_provider_t;
  Pxcb_randr_lease_t = ^xcb_randr_lease_t;
  Pxcb_randr_screen_size_t = ^xcb_randr_screen_size_t;
  Pxcb_randr_refresh_rates_t = ^xcb_randr_refresh_rates_t;
  Pxcb_randr_mode_info_t = ^xcb_randr_mode_info_t;
  Pxcb_randr_crtc_change_t = ^xcb_randr_crtc_change_t;
  Pxcb_randr_output_change_t = ^xcb_randr_output_change_t;
  Pxcb_randr_output_property_t = ^xcb_randr_output_property_t;
  Pxcb_randr_provider_change_t = ^xcb_randr_provider_change_t;
  Pxcb_randr_provider_property_t = ^xcb_randr_provider_property_t;
  Pxcb_randr_resource_change_t = ^xcb_randr_resource_change_t;
  Pxcb_randr_monitor_info_t = ^xcb_randr_monitor_info_t;
  Pxcb_randr_lease_notify_t = ^xcb_randr_lease_notify_t;
  Pxcb_randr_notify_data_t = ^xcb_randr_notify_data_t;
  Pxcb_randr_mode_iterator_t = ^xcb_randr_mode_iterator_t;
  Pxcb_randr_crtc_iterator_t = ^xcb_randr_crtc_iterator_t;
  Pxcb_randr_output_iterator_t = ^xcb_randr_output_iterator_t;
  Pxcb_randr_provider_iterator_t = ^xcb_randr_provider_iterator_t;
  Pxcb_randr_lease_iterator_t = ^xcb_randr_lease_iterator_t;
  Pxcb_randr_screen_size_iterator_t = ^xcb_randr_screen_size_iterator_t;
  PWord = ^Word;
  Pxcb_randr_refresh_rates_iterator_t = ^xcb_randr_refresh_rates_iterator_t;
  Pxcb_connection_t = ^xcb_connection_t;
  Pxcb_randr_query_version_reply_t = ^xcb_randr_query_version_reply_t;
  Pxcb_generic_error_t = ^xcb_generic_error_t;
  PPxcb_generic_error_t = ^Pxcb_generic_error_t;
  Pxcb_randr_set_screen_config_reply_t = ^xcb_randr_set_screen_config_reply_t;
  Pxcb_randr_get_screen_info_reply_t = ^xcb_randr_get_screen_info_reply_t;
  Pxcb_randr_get_screen_size_range_reply_t = ^xcb_randr_get_screen_size_range_reply_t;
  Pxcb_randr_mode_info_iterator_t = ^xcb_randr_mode_info_iterator_t;
  Pxcb_randr_get_screen_resources_reply_t = ^xcb_randr_get_screen_resources_reply_t;
  PByte = ^Byte;
  Pxcb_randr_get_output_info_reply_t = ^xcb_randr_get_output_info_reply_t;
  Pxcb_atom_t = ^xcb_atom_t;
  Pxcb_randr_list_output_properties_reply_t = ^xcb_randr_list_output_properties_reply_t;
  PInteger = ^Integer;
  Pxcb_randr_query_output_property_reply_t = ^xcb_randr_query_output_property_reply_t;
  Pxcb_randr_configure_output_property_request_t = ^xcb_randr_configure_output_property_request_t;
  Pxcb_randr_change_output_property_request_t = ^xcb_randr_change_output_property_request_t;
  Pxcb_randr_get_output_property_reply_t = ^xcb_randr_get_output_property_reply_t;
  Pxcb_randr_create_mode_reply_t = ^xcb_randr_create_mode_reply_t;
  Pxcb_randr_get_crtc_info_reply_t = ^xcb_randr_get_crtc_info_reply_t;
  Pxcb_randr_set_crtc_config_reply_t = ^xcb_randr_set_crtc_config_reply_t;
  Pxcb_randr_get_crtc_gamma_size_reply_t = ^xcb_randr_get_crtc_gamma_size_reply_t;
  Pxcb_randr_get_crtc_gamma_reply_t = ^xcb_randr_get_crtc_gamma_reply_t;
  Pxcb_randr_set_crtc_gamma_request_t = ^xcb_randr_set_crtc_gamma_request_t;
  Pxcb_randr_get_screen_resources_current_reply_t = ^xcb_randr_get_screen_resources_current_reply_t;
  Pxcb_render_fixed_t = ^xcb_render_fixed_t;
  Pxcb_randr_set_crtc_transform_request_t = ^xcb_randr_set_crtc_transform_request_t;
  Pxcb_randr_get_crtc_transform_reply_t = ^xcb_randr_get_crtc_transform_reply_t;
  Pxcb_randr_get_panning_reply_t = ^xcb_randr_get_panning_reply_t;
  Pxcb_randr_set_panning_reply_t = ^xcb_randr_set_panning_reply_t;
  Pxcb_randr_get_output_primary_reply_t = ^xcb_randr_get_output_primary_reply_t;
  Pxcb_randr_get_providers_reply_t = ^xcb_randr_get_providers_reply_t;
  Pxcb_randr_get_provider_info_reply_t = ^xcb_randr_get_provider_info_reply_t;
  PCardinal = ^Cardinal;
  Pxcb_randr_list_provider_properties_reply_t = ^xcb_randr_list_provider_properties_reply_t;
  Pxcb_randr_query_provider_property_reply_t = ^xcb_randr_query_provider_property_reply_t;
  Pxcb_randr_configure_provider_property_request_t = ^xcb_randr_configure_provider_property_request_t;
  Pxcb_randr_change_provider_property_request_t = ^xcb_randr_change_provider_property_request_t;
  Pxcb_randr_get_provider_property_reply_t = ^xcb_randr_get_provider_property_reply_t;
  Pxcb_randr_crtc_change_iterator_t = ^xcb_randr_crtc_change_iterator_t;
  Pxcb_randr_output_change_iterator_t = ^xcb_randr_output_change_iterator_t;
  Pxcb_randr_output_property_iterator_t = ^xcb_randr_output_property_iterator_t;
  Pxcb_randr_provider_change_iterator_t = ^xcb_randr_provider_change_iterator_t;
  Pxcb_randr_provider_property_iterator_t = ^xcb_randr_provider_property_iterator_t;
  Pxcb_randr_resource_change_iterator_t = ^xcb_randr_resource_change_iterator_t;
  Pxcb_randr_monitor_info_iterator_t = ^xcb_randr_monitor_info_iterator_t;
  Pxcb_randr_get_monitors_reply_t = ^xcb_randr_get_monitors_reply_t;
  Pxcb_randr_set_monitor_request_t = ^xcb_randr_set_monitor_request_t;
  Pxcb_randr_create_lease_reply_t = ^xcb_randr_create_lease_reply_t;
  Pxcb_randr_lease_notify_iterator_t = ^xcb_randr_lease_notify_iterator_t;
  Pxcb_randr_notify_data_iterator_t = ^xcb_randr_notify_data_iterator_t;
  xcb_randr_mode_t = Cardinal;
  xcb_randr_mode_iterator_t = record
    data: Pxcb_randr_mode_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_randr_crtc_t = Cardinal;
  xcb_randr_crtc_iterator_t = record
    data: Pxcb_randr_crtc_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_randr_output_t = Cardinal;
  xcb_randr_output_iterator_t = record
    data: Pxcb_randr_output_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_randr_provider_t = Cardinal;
  xcb_randr_provider_iterator_t = record
    data: Pxcb_randr_provider_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_randr_lease_t = Cardinal;
  xcb_randr_lease_iterator_t = record
    data: Pxcb_randr_lease_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_randr_bad_output_error_t = record
    response_type: Byte;
    error_code: Byte;
    sequence: Word;
    bad_value: Cardinal;
    minor_opcode: Word;
    major_opcode: Byte;
  end;
  xcb_randr_bad_crtc_error_t = record
    response_type: Byte;
    error_code: Byte;
    sequence: Word;
    bad_value: Cardinal;
    minor_opcode: Word;
    major_opcode: Byte;
  end;
  xcb_randr_bad_mode_error_t = record
    response_type: Byte;
    error_code: Byte;
    sequence: Word;
    bad_value: Cardinal;
    minor_opcode: Word;
    major_opcode: Byte;
  end;
  xcb_randr_bad_provider_error_t = record
    response_type: Byte;
    error_code: Byte;
    sequence: Word;
    bad_value: Cardinal;
    minor_opcode: Word;
    major_opcode: Byte;
  end;
  xcb_randr_rotation_t = Integer;
  xcb_randr_screen_size_t = record
    width: Word;
    height: Word;
    mwidth: Word;
    mheight: Word;
  end;
  xcb_randr_screen_size_iterator_t = record
    data: Pxcb_randr_screen_size_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_randr_refresh_rates_t = record
    nRates: Word;
  end;
  xcb_randr_refresh_rates_iterator_t = record
    data: Pxcb_randr_refresh_rates_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_randr_query_version_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_query_version_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    major_version: Cardinal;
    minor_version: Cardinal;
  end;
  xcb_randr_query_version_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    major_version: Cardinal;
    minor_version: Cardinal;
    pad1: array[0..15] of Byte;
  end;
  xcb_randr_set_config_t = Integer;
  xcb_randr_set_screen_config_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_set_screen_config_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    window: xcb_window_t;
    timestamp: xcb_timestamp_t;
    config_timestamp: xcb_timestamp_t;
    sizeID: Word;
    rotation: Word;
    rate: Word;
    pad0: array[0..1] of Byte;
  end;
  xcb_randr_set_screen_config_reply_t = record
    response_type: Byte;
    status: Byte;
    sequence: Word;
    length: Cardinal;
    new_timestamp: xcb_timestamp_t;
    config_timestamp: xcb_timestamp_t;
    root: xcb_window_t;
    subpixel_order: Word;
    pad0: array[0..9] of Byte;
  end;
  xcb_randr_notify_mask_t = Integer;
  xcb_randr_select_input_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    window: xcb_window_t;
    enable: Word;
    pad0: array[0..1] of Byte;
  end;
  xcb_randr_get_screen_info_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_get_screen_info_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    window: xcb_window_t;
  end;
  xcb_randr_get_screen_info_reply_t = record
    response_type: Byte;
    rotations: Byte;
    sequence: Word;
    length: Cardinal;
    root: xcb_window_t;
    timestamp: xcb_timestamp_t;
    config_timestamp: xcb_timestamp_t;
    nSizes: Word;
    sizeID: Word;
    rotation: Word;
    rate: Word;
    nInfo: Word;
    pad0: array[0..1] of Byte;
  end;
  xcb_randr_get_screen_size_range_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_get_screen_size_range_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    window: xcb_window_t;
  end;
  xcb_randr_get_screen_size_range_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    min_width: Word;
    min_height: Word;
    max_width: Word;
    max_height: Word;
    pad1: array[0..15] of Byte;
  end;
  xcb_randr_set_screen_size_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    window: xcb_window_t;
    width: Word;
    height: Word;
    mm_width: Cardinal;
    mm_height: Cardinal;
  end;
  xcb_randr_mode_flag_t = Integer;
  xcb_randr_mode_info_t = record
    id: Cardinal;
    width: Word;
    height: Word;
    dot_clock: Cardinal;
    hsync_start: Word;
    hsync_end: Word;
    htotal: Word;
    hskew: Word;
    vsync_start: Word;
    vsync_end: Word;
    vtotal: Word;
    name_len: Word;
    mode_flags: Cardinal;
  end;
  xcb_randr_mode_info_iterator_t = record
    data: Pxcb_randr_mode_info_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_randr_get_screen_resources_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_get_screen_resources_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    window: xcb_window_t;
  end;
  xcb_randr_get_screen_resources_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    timestamp: xcb_timestamp_t;
    config_timestamp: xcb_timestamp_t;
    num_crtcs: Word;
    num_outputs: Word;
    num_modes: Word;
    names_len: Word;
    pad1: array[0..7] of Byte;
  end;
  xcb_randr_connection_t = Integer;
  xcb_randr_get_output_info_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_get_output_info_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    output: xcb_randr_output_t;
    config_timestamp: xcb_timestamp_t;
  end;
  xcb_randr_get_output_info_reply_t = record
    response_type: Byte;
    status: Byte;
    sequence: Word;
    length: Cardinal;
    timestamp: xcb_timestamp_t;
    crtc: xcb_randr_crtc_t;
    mm_width: Cardinal;
    mm_height: Cardinal;
    connection: Byte;
    subpixel_order: Byte;
    num_crtcs: Word;
    num_modes: Word;
    num_preferred: Word;
    num_clones: Word;
    name_len: Word;
  end;
  xcb_randr_list_output_properties_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_list_output_properties_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    output: xcb_randr_output_t;
  end;
  xcb_randr_list_output_properties_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    num_atoms: Word;
    pad1: array[0..21] of Byte;
  end;
  xcb_randr_query_output_property_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_query_output_property_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    output: xcb_randr_output_t;
    property_: xcb_atom_t;
  end;
  xcb_randr_query_output_property_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    pending: Byte;
    range: Byte;
    immutable: Byte;
    pad1: array[0..20] of Byte;
  end;
  xcb_randr_configure_output_property_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    output: xcb_randr_output_t;
    property_: xcb_atom_t;
    pending: Byte;
    range: Byte;
    pad0: array[0..1] of Byte;
  end;
  xcb_randr_change_output_property_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    output: xcb_randr_output_t;
    property_: xcb_atom_t;
    type_: xcb_atom_t;
    format: Byte;
    mode: Byte;
    pad0: array[0..1] of Byte;
    num_units: Cardinal;
  end;
  xcb_randr_delete_output_property_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    output: xcb_randr_output_t;
    property_: xcb_atom_t;
  end;
  xcb_randr_get_output_property_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_get_output_property_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    output: xcb_randr_output_t;
    property_: xcb_atom_t;
    type_: xcb_atom_t;
    long_offset: Cardinal;
    long_length: Cardinal;
    _delete: Byte;
    pending: Byte;
    pad0: array[0..1] of Byte;
  end;
  xcb_randr_get_output_property_reply_t = record
    response_type: Byte;
    format: Byte;
    sequence: Word;
    length: Cardinal;
    type_: xcb_atom_t;
    bytes_after: Cardinal;
    num_items: Cardinal;
    pad0: array[0..11] of Byte;
  end;
  xcb_randr_create_mode_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_create_mode_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    window: xcb_window_t;
    mode_info: xcb_randr_mode_info_t;
  end;
  xcb_randr_create_mode_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    mode: xcb_randr_mode_t;
    pad1: array[0..19] of Byte;
  end;
  xcb_randr_destroy_mode_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    mode: xcb_randr_mode_t;
  end;
  xcb_randr_add_output_mode_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    output: xcb_randr_output_t;
    mode: xcb_randr_mode_t;
  end;
  xcb_randr_delete_output_mode_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    output: xcb_randr_output_t;
    mode: xcb_randr_mode_t;
  end;
  xcb_randr_get_crtc_info_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_get_crtc_info_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    crtc: xcb_randr_crtc_t;
    config_timestamp: xcb_timestamp_t;
  end;
  xcb_randr_get_crtc_info_reply_t = record
    response_type: Byte;
    status: Byte;
    sequence: Word;
    length: Cardinal;
    timestamp: xcb_timestamp_t;
    x: SmallInt;
    y: SmallInt;
    width: Word;
    height: Word;
    mode: xcb_randr_mode_t;
    rotation: Word;
    rotations: Word;
    num_outputs: Word;
    num_possible_outputs: Word;
  end;
  xcb_randr_set_crtc_config_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_set_crtc_config_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    crtc: xcb_randr_crtc_t;
    timestamp: xcb_timestamp_t;
    config_timestamp: xcb_timestamp_t;
    x: SmallInt;
    y: SmallInt;
    mode: xcb_randr_mode_t;
    rotation: Word;
    pad0: array[0..1] of Byte;
  end;
  xcb_randr_set_crtc_config_reply_t = record
    response_type: Byte;
    status: Byte;
    sequence: Word;
    length: Cardinal;
    timestamp: xcb_timestamp_t;
    pad0: array[0..19] of Byte;
  end;
  xcb_randr_get_crtc_gamma_size_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_get_crtc_gamma_size_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    crtc: xcb_randr_crtc_t;
  end;
  xcb_randr_get_crtc_gamma_size_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    size: Word;
    pad1: array[0..21] of Byte;
  end;
  xcb_randr_get_crtc_gamma_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_get_crtc_gamma_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    crtc: xcb_randr_crtc_t;
  end;
  xcb_randr_get_crtc_gamma_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    size: Word;
    pad1: array[0..21] of Byte;
  end;
  xcb_randr_set_crtc_gamma_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    crtc: xcb_randr_crtc_t;
    size: Word;
    pad0: array[0..1] of Byte;
  end;
  xcb_randr_get_screen_resources_current_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_get_screen_resources_current_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    window: xcb_window_t;
  end;
  xcb_randr_get_screen_resources_current_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    timestamp: xcb_timestamp_t;
    config_timestamp: xcb_timestamp_t;
    num_crtcs: Word;
    num_outputs: Word;
    num_modes: Word;
    names_len: Word;
    pad1: array[0..7] of Byte;
  end;
  xcb_randr_transform_t = Integer;
  xcb_randr_set_crtc_transform_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    crtc: xcb_randr_crtc_t;
    transform: xcb_render_transform_t;
    filter_len: Word;
    pad0: array[0..1] of Byte;
  end;
  xcb_randr_get_crtc_transform_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_get_crtc_transform_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    crtc: xcb_randr_crtc_t;
  end;
  xcb_randr_get_crtc_transform_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    pending_transform: xcb_render_transform_t;
    has_transforms: Byte;
    pad1: array[0..2] of Byte;
    current_transform: xcb_render_transform_t;
    pad2: array[0..3] of Byte;
    pending_len: Word;
    pending_nparams: Word;
    current_len: Word;
    current_nparams: Word;
  end;
  xcb_randr_get_panning_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_get_panning_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    crtc: xcb_randr_crtc_t;
  end;
  xcb_randr_get_panning_reply_t = record
    response_type: Byte;
    status: Byte;
    sequence: Word;
    length: Cardinal;
    timestamp: xcb_timestamp_t;
    left: Word;
    top: Word;
    width: Word;
    height: Word;
    track_left: Word;
    track_top: Word;
    track_width: Word;
    track_height: Word;
    border_left: SmallInt;
    border_top: SmallInt;
    border_right: SmallInt;
    border_bottom: SmallInt;
  end;
  xcb_randr_set_panning_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_set_panning_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    crtc: xcb_randr_crtc_t;
    timestamp: xcb_timestamp_t;
    left: Word;
    top: Word;
    width: Word;
    height: Word;
    track_left: Word;
    track_top: Word;
    track_width: Word;
    track_height: Word;
    border_left: SmallInt;
    border_top: SmallInt;
    border_right: SmallInt;
    border_bottom: SmallInt;
  end;
  xcb_randr_set_panning_reply_t = record
    response_type: Byte;
    status: Byte;
    sequence: Word;
    length: Cardinal;
    timestamp: xcb_timestamp_t;
  end;
  xcb_randr_set_output_primary_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    window: xcb_window_t;
    output: xcb_randr_output_t;
  end;
  xcb_randr_get_output_primary_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_get_output_primary_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    window: xcb_window_t;
  end;
  xcb_randr_get_output_primary_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    output: xcb_randr_output_t;
  end;
  xcb_randr_get_providers_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_get_providers_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    window: xcb_window_t;
  end;
  xcb_randr_get_providers_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    timestamp: xcb_timestamp_t;
    num_providers: Word;
    pad1: array[0..17] of Byte;
  end;
  xcb_randr_provider_capability_t = Integer;
  xcb_randr_get_provider_info_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_get_provider_info_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    provider: xcb_randr_provider_t;
    config_timestamp: xcb_timestamp_t;
  end;
  xcb_randr_get_provider_info_reply_t = record
    response_type: Byte;
    status: Byte;
    sequence: Word;
    length: Cardinal;
    timestamp: xcb_timestamp_t;
    capabilities: Cardinal;
    num_crtcs: Word;
    num_outputs: Word;
    num_associated_providers: Word;
    name_len: Word;
    pad0: array[0..7] of Byte;
  end;
  xcb_randr_set_provider_offload_sink_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    provider: xcb_randr_provider_t;
    sink_provider: xcb_randr_provider_t;
    config_timestamp: xcb_timestamp_t;
  end;
  xcb_randr_set_provider_output_source_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    provider: xcb_randr_provider_t;
    source_provider: xcb_randr_provider_t;
    config_timestamp: xcb_timestamp_t;
  end;
  xcb_randr_list_provider_properties_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_list_provider_properties_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    provider: xcb_randr_provider_t;
  end;
  xcb_randr_list_provider_properties_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    num_atoms: Word;
    pad1: array[0..21] of Byte;
  end;
  xcb_randr_query_provider_property_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_query_provider_property_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    provider: xcb_randr_provider_t;
    property_: xcb_atom_t;
  end;
  xcb_randr_query_provider_property_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    pending: Byte;
    range: Byte;
    immutable: Byte;
    pad1: array[0..20] of Byte;
  end;
  xcb_randr_configure_provider_property_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    provider: xcb_randr_provider_t;
    property_: xcb_atom_t;
    pending: Byte;
    range: Byte;
    pad0: array[0..1] of Byte;
  end;
  xcb_randr_change_provider_property_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    provider: xcb_randr_provider_t;
    property_: xcb_atom_t;
    type_: xcb_atom_t;
    format: Byte;
    mode: Byte;
    pad0: array[0..1] of Byte;
    num_items: Cardinal;
  end;
  xcb_randr_delete_provider_property_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    provider: xcb_randr_provider_t;
    property_: xcb_atom_t;
  end;
  xcb_randr_get_provider_property_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_get_provider_property_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    provider: xcb_randr_provider_t;
    property_: xcb_atom_t;
    type_: xcb_atom_t;
    long_offset: Cardinal;
    long_length: Cardinal;
    _delete: Byte;
    pending: Byte;
    pad0: array[0..1] of Byte;
  end;
  xcb_randr_get_provider_property_reply_t = record
    response_type: Byte;
    format: Byte;
    sequence: Word;
    length: Cardinal;
    type_: xcb_atom_t;
    bytes_after: Cardinal;
    num_items: Cardinal;
    pad0: array[0..11] of Byte;
  end;
  xcb_randr_screen_change_notify_event_t = record
    response_type: Byte;
    rotation: Byte;
    sequence: Word;
    timestamp: xcb_timestamp_t;
    config_timestamp: xcb_timestamp_t;
    root: xcb_window_t;
    request_window: xcb_window_t;
    sizeID: Word;
    subpixel_order: Word;
    width: Word;
    height: Word;
    mwidth: Word;
    mheight: Word;
  end;
  xcb_randr_notify_t = Integer;
  xcb_randr_crtc_change_t = record
    timestamp: xcb_timestamp_t;
    window: xcb_window_t;
    crtc: xcb_randr_crtc_t;
    mode: xcb_randr_mode_t;
    rotation: Word;
    pad0: array[0..1] of Byte;
    x: SmallInt;
    y: SmallInt;
    width: Word;
    height: Word;
  end;
  xcb_randr_crtc_change_iterator_t = record
    data: Pxcb_randr_crtc_change_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_randr_output_change_t = record
    timestamp: xcb_timestamp_t;
    config_timestamp: xcb_timestamp_t;
    window: xcb_window_t;
    output: xcb_randr_output_t;
    crtc: xcb_randr_crtc_t;
    mode: xcb_randr_mode_t;
    rotation: Word;
    connection: Byte;
    subpixel_order: Byte;
  end;
  xcb_randr_output_change_iterator_t = record
    data: Pxcb_randr_output_change_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_randr_output_property_t = record
    window: xcb_window_t;
    output: xcb_randr_output_t;
    atom: xcb_atom_t;
    timestamp: xcb_timestamp_t;
    status: Byte;
    pad0: array[0..10] of Byte;
  end;
  xcb_randr_output_property_iterator_t = record
    data: Pxcb_randr_output_property_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_randr_provider_change_t = record
    timestamp: xcb_timestamp_t;
    window: xcb_window_t;
    provider: xcb_randr_provider_t;
    pad0: array[0..15] of Byte;
  end;
  xcb_randr_provider_change_iterator_t = record
    data: Pxcb_randr_provider_change_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_randr_provider_property_t = record
    window: xcb_window_t;
    provider: xcb_randr_provider_t;
    atom: xcb_atom_t;
    timestamp: xcb_timestamp_t;
    state: Byte;
    pad0: array[0..10] of Byte;
  end;
  xcb_randr_provider_property_iterator_t = record
    data: Pxcb_randr_provider_property_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_randr_resource_change_t = record
    timestamp: xcb_timestamp_t;
    window: xcb_window_t;
    pad0: array[0..19] of Byte;
  end;
  xcb_randr_resource_change_iterator_t = record
    data: Pxcb_randr_resource_change_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_randr_monitor_info_t = record
    name: xcb_atom_t;
    primary: Byte;
    automatic: Byte;
    nOutput: Word;
    x: SmallInt;
    y: SmallInt;
    width: Word;
    height: Word;
    width_in_millimeters: Cardinal;
    height_in_millimeters: Cardinal;
  end;
  xcb_randr_monitor_info_iterator_t = record
    data: Pxcb_randr_monitor_info_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_randr_get_monitors_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_get_monitors_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    window: xcb_window_t;
    get_active: Byte;
  end;
  xcb_randr_get_monitors_reply_t = record
    response_type: Byte;
    pad0: Byte;
    sequence: Word;
    length: Cardinal;
    timestamp: xcb_timestamp_t;
    nMonitors: Cardinal;
    nOutputs: Cardinal;
    pad1: array[0..11] of Byte;
  end;
  xcb_randr_set_monitor_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    window: xcb_window_t;
  end;
  xcb_randr_delete_monitor_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    window: xcb_window_t;
    name: xcb_atom_t;
  end;
  xcb_randr_create_lease_cookie_t = record
    sequence: Cardinal;
  end;
  xcb_randr_create_lease_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    window: xcb_window_t;
    lid: xcb_randr_lease_t;
    num_crtcs: Word;
    num_outputs: Word;
  end;
  xcb_randr_create_lease_reply_t = record
    response_type: Byte;
    nfd: Byte;
    sequence: Word;
    length: Cardinal;
    pad0: array[0..23] of Byte;
  end;
  xcb_randr_free_lease_request_t = record
    major_opcode: Byte;
    minor_opcode: Byte;
    length: Word;
    lid: xcb_randr_lease_t;
    terminate: Byte;
  end;
  xcb_randr_lease_notify_t = record
    timestamp: xcb_timestamp_t;
    window: xcb_window_t;
    lease: xcb_randr_lease_t;
    created: Byte;
    pad0: array[0..14] of Byte;
  end;
  xcb_randr_lease_notify_iterator_t = record
    data: Pxcb_randr_lease_notify_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_randr_notify_data_t = record end; { TODO: C union of unknown size — placeholder, only valid through pointers }
  xcb_randr_notify_data_iterator_t = record
    data: Pxcb_randr_notify_data_t;
    rem: Integer;
    index: Integer;
  end;
  xcb_randr_notify_event_t = record
    response_type: Byte;
    subCode: Byte;
    sequence: Word;
    u: xcb_randr_notify_data_t;
  end;

const
  XCB_RANDR_ROTATION_ROTATE_0 = 1;
  XCB_RANDR_ROTATION_ROTATE_90 = 2;
  XCB_RANDR_ROTATION_ROTATE_180 = 4;
  XCB_RANDR_ROTATION_ROTATE_270 = 8;
  XCB_RANDR_ROTATION_REFLECT_X = 16;
  XCB_RANDR_ROTATION_REFLECT_Y = 32;
  XCB_RANDR_SET_CONFIG_SUCCESS = 0;
  XCB_RANDR_SET_CONFIG_INVALID_CONFIG_TIME = 1;
  XCB_RANDR_SET_CONFIG_INVALID_TIME = 2;
  XCB_RANDR_SET_CONFIG_FAILED = 3;
  XCB_RANDR_NOTIFY_MASK_SCREEN_CHANGE = 1;
  XCB_RANDR_NOTIFY_MASK_CRTC_CHANGE = 2;
  XCB_RANDR_NOTIFY_MASK_OUTPUT_CHANGE = 4;
  XCB_RANDR_NOTIFY_MASK_OUTPUT_PROPERTY = 8;
  XCB_RANDR_NOTIFY_MASK_PROVIDER_CHANGE = 16;
  XCB_RANDR_NOTIFY_MASK_PROVIDER_PROPERTY = 32;
  XCB_RANDR_NOTIFY_MASK_RESOURCE_CHANGE = 64;
  XCB_RANDR_NOTIFY_MASK_LEASE = 128;
  XCB_RANDR_MODE_FLAG_HSYNC_POSITIVE = 1;
  XCB_RANDR_MODE_FLAG_HSYNC_NEGATIVE = 2;
  XCB_RANDR_MODE_FLAG_VSYNC_POSITIVE = 4;
  XCB_RANDR_MODE_FLAG_VSYNC_NEGATIVE = 8;
  XCB_RANDR_MODE_FLAG_INTERLACE = 16;
  XCB_RANDR_MODE_FLAG_DOUBLE_SCAN = 32;
  XCB_RANDR_MODE_FLAG_CSYNC = 64;
  XCB_RANDR_MODE_FLAG_CSYNC_POSITIVE = 128;
  XCB_RANDR_MODE_FLAG_CSYNC_NEGATIVE = 256;
  XCB_RANDR_MODE_FLAG_HSKEW_PRESENT = 512;
  XCB_RANDR_MODE_FLAG_BCAST = 1024;
  XCB_RANDR_MODE_FLAG_PIXEL_MULTIPLEX = 2048;
  XCB_RANDR_MODE_FLAG_DOUBLE_CLOCK = 4096;
  XCB_RANDR_MODE_FLAG_HALVE_CLOCK = 8192;
  XCB_RANDR_CONNECTION_CONNECTED = 0;
  XCB_RANDR_CONNECTION_DISCONNECTED = 1;
  XCB_RANDR_CONNECTION_UNKNOWN = 2;
  XCB_RANDR_TRANSFORM_UNIT = 1;
  XCB_RANDR_TRANSFORM_SCALE_UP = 2;
  XCB_RANDR_TRANSFORM_SCALE_DOWN = 4;
  XCB_RANDR_TRANSFORM_PROJECTIVE = 8;
  XCB_RANDR_PROVIDER_CAPABILITY_SOURCE_OUTPUT = 1;
  XCB_RANDR_PROVIDER_CAPABILITY_SINK_OUTPUT = 2;
  XCB_RANDR_PROVIDER_CAPABILITY_SOURCE_OFFLOAD = 4;
  XCB_RANDR_PROVIDER_CAPABILITY_SINK_OFFLOAD = 8;
  XCB_RANDR_NOTIFY_CRTC_CHANGE = 0;
  XCB_RANDR_NOTIFY_OUTPUT_CHANGE = 1;
  XCB_RANDR_NOTIFY_OUTPUT_PROPERTY = 2;
  XCB_RANDR_NOTIFY_PROVIDER_CHANGE = 3;
  XCB_RANDR_NOTIFY_PROVIDER_PROPERTY = 4;
  XCB_RANDR_NOTIFY_RESOURCE_CHANGE = 5;
  XCB_RANDR_NOTIFY_LEASE = 6;
  XCB_RANDR_MAJOR_VERSION = 1;
  XCB_RANDR_MINOR_VERSION = 6;
  XCB_RANDR_BAD_OUTPUT = 0;
  XCB_RANDR_BAD_CRTC = 1;
  XCB_RANDR_BAD_MODE = 2;
  XCB_RANDR_BAD_PROVIDER = 3;
  XCB_RANDR_SCREEN_CHANGE_NOTIFY = 0;
  XCB_RANDR_NOTIFY = 1;

procedure xcb_randr_mode_next(i: Pxcb_randr_mode_iterator_t); cdecl; external 'xcb-randr' name 'xcb_randr_mode_next';
{ xcb_randr_mode_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_randr_crtc_next(i: Pxcb_randr_crtc_iterator_t); cdecl; external 'xcb-randr' name 'xcb_randr_crtc_next';
{ xcb_randr_crtc_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_randr_output_next(i: Pxcb_randr_output_iterator_t); cdecl; external 'xcb-randr' name 'xcb_randr_output_next';
{ xcb_randr_output_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_randr_provider_next(i: Pxcb_randr_provider_iterator_t); cdecl; external 'xcb-randr' name 'xcb_randr_provider_next';
{ xcb_randr_provider_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_randr_lease_next(i: Pxcb_randr_lease_iterator_t); cdecl; external 'xcb-randr' name 'xcb_randr_lease_next';
{ xcb_randr_lease_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_randr_screen_size_next(i: Pxcb_randr_screen_size_iterator_t); cdecl; external 'xcb-randr' name 'xcb_randr_screen_size_next';
{ xcb_randr_screen_size_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_refresh_rates_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_refresh_rates_sizeof';
function xcb_randr_refresh_rates_rates(R: Pxcb_randr_refresh_rates_t): PWord; cdecl; external 'xcb-randr' name 'xcb_randr_refresh_rates_rates';
function xcb_randr_refresh_rates_rates_length(R: Pxcb_randr_refresh_rates_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_refresh_rates_rates_length';
{ xcb_randr_refresh_rates_rates_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_randr_refresh_rates_next(i: Pxcb_randr_refresh_rates_iterator_t); cdecl; external 'xcb-randr' name 'xcb_randr_refresh_rates_next';
{ xcb_randr_refresh_rates_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_query_version(c: Pxcb_connection_t; major_version: Cardinal; minor_version: Cardinal): xcb_randr_query_version_cookie_t; cdecl; external 'xcb-randr' name 'xcb_randr_query_version';
function xcb_randr_query_version_unchecked(c: Pxcb_connection_t; major_version: Cardinal; minor_version: Cardinal): xcb_randr_query_version_cookie_t; cdecl; external 'xcb-randr' name 'xcb_randr_query_version_unchecked';
function xcb_randr_query_version_reply(c: Pxcb_connection_t; cookie: xcb_randr_query_version_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_query_version_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_query_version_reply';
{ xcb_randr_set_screen_config: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
{ xcb_randr_set_screen_config_unchecked: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
function xcb_randr_set_screen_config_reply(c: Pxcb_connection_t; cookie: xcb_randr_set_screen_config_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_set_screen_config_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_set_screen_config_reply';
{ xcb_randr_select_input_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_select_input: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_randr_get_screen_info_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_info_sizeof';
{ xcb_randr_get_screen_info: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
{ xcb_randr_get_screen_info_unchecked: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
function xcb_randr_get_screen_info_sizes(R: Pxcb_randr_get_screen_info_reply_t): Pxcb_randr_screen_size_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_info_sizes';
function xcb_randr_get_screen_info_sizes_length(R: Pxcb_randr_get_screen_info_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_info_sizes_length';
function xcb_randr_get_screen_info_sizes_iterator(R: Pxcb_randr_get_screen_info_reply_t): xcb_randr_screen_size_iterator_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_info_sizes_iterator';
function xcb_randr_get_screen_info_rates_length(R: Pxcb_randr_get_screen_info_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_info_rates_length';
function xcb_randr_get_screen_info_rates_iterator(R: Pxcb_randr_get_screen_info_reply_t): xcb_randr_refresh_rates_iterator_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_info_rates_iterator';
function xcb_randr_get_screen_info_reply(c: Pxcb_connection_t; cookie: xcb_randr_get_screen_info_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_get_screen_info_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_info_reply';
{ xcb_randr_get_screen_size_range: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
{ xcb_randr_get_screen_size_range_unchecked: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
function xcb_randr_get_screen_size_range_reply(c: Pxcb_connection_t; cookie: xcb_randr_get_screen_size_range_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_get_screen_size_range_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_size_range_reply';
{ xcb_randr_set_screen_size_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_set_screen_size: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
procedure xcb_randr_mode_info_next(i: Pxcb_randr_mode_info_iterator_t); cdecl; external 'xcb-randr' name 'xcb_randr_mode_info_next';
{ xcb_randr_mode_info_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_screen_resources_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_resources_sizeof';
{ xcb_randr_get_screen_resources: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
{ xcb_randr_get_screen_resources_unchecked: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
function xcb_randr_get_screen_resources_crtcs(R: Pxcb_randr_get_screen_resources_reply_t): Pxcb_randr_crtc_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_resources_crtcs';
function xcb_randr_get_screen_resources_crtcs_length(R: Pxcb_randr_get_screen_resources_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_resources_crtcs_length';
{ xcb_randr_get_screen_resources_crtcs_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_screen_resources_outputs(R: Pxcb_randr_get_screen_resources_reply_t): Pxcb_randr_output_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_resources_outputs';
function xcb_randr_get_screen_resources_outputs_length(R: Pxcb_randr_get_screen_resources_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_resources_outputs_length';
{ xcb_randr_get_screen_resources_outputs_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_screen_resources_modes(R: Pxcb_randr_get_screen_resources_reply_t): Pxcb_randr_mode_info_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_resources_modes';
function xcb_randr_get_screen_resources_modes_length(R: Pxcb_randr_get_screen_resources_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_resources_modes_length';
function xcb_randr_get_screen_resources_modes_iterator(R: Pxcb_randr_get_screen_resources_reply_t): xcb_randr_mode_info_iterator_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_resources_modes_iterator';
function xcb_randr_get_screen_resources_names(R: Pxcb_randr_get_screen_resources_reply_t): PByte; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_resources_names';
function xcb_randr_get_screen_resources_names_length(R: Pxcb_randr_get_screen_resources_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_resources_names_length';
{ xcb_randr_get_screen_resources_names_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_screen_resources_reply(c: Pxcb_connection_t; cookie: xcb_randr_get_screen_resources_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_get_screen_resources_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_resources_reply';
function xcb_randr_get_output_info_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_output_info_sizeof';
{ xcb_randr_get_output_info: skipped — parameter type 'xcb_timestamp_t' comes from a filtered-out header }
{ xcb_randr_get_output_info_unchecked: skipped — parameter type 'xcb_timestamp_t' comes from a filtered-out header }
function xcb_randr_get_output_info_crtcs(R: Pxcb_randr_get_output_info_reply_t): Pxcb_randr_crtc_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_output_info_crtcs';
function xcb_randr_get_output_info_crtcs_length(R: Pxcb_randr_get_output_info_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_output_info_crtcs_length';
{ xcb_randr_get_output_info_crtcs_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_output_info_modes(R: Pxcb_randr_get_output_info_reply_t): Pxcb_randr_mode_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_output_info_modes';
function xcb_randr_get_output_info_modes_length(R: Pxcb_randr_get_output_info_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_output_info_modes_length';
{ xcb_randr_get_output_info_modes_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_output_info_clones(R: Pxcb_randr_get_output_info_reply_t): Pxcb_randr_output_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_output_info_clones';
function xcb_randr_get_output_info_clones_length(R: Pxcb_randr_get_output_info_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_output_info_clones_length';
{ xcb_randr_get_output_info_clones_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_output_info_name(R: Pxcb_randr_get_output_info_reply_t): PByte; cdecl; external 'xcb-randr' name 'xcb_randr_get_output_info_name';
function xcb_randr_get_output_info_name_length(R: Pxcb_randr_get_output_info_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_output_info_name_length';
{ xcb_randr_get_output_info_name_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_output_info_reply(c: Pxcb_connection_t; cookie: xcb_randr_get_output_info_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_get_output_info_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_output_info_reply';
function xcb_randr_list_output_properties_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_list_output_properties_sizeof';
function xcb_randr_list_output_properties(c: Pxcb_connection_t; output: xcb_randr_output_t): xcb_randr_list_output_properties_cookie_t; cdecl; external 'xcb-randr' name 'xcb_randr_list_output_properties';
function xcb_randr_list_output_properties_unchecked(c: Pxcb_connection_t; output: xcb_randr_output_t): xcb_randr_list_output_properties_cookie_t; cdecl; external 'xcb-randr' name 'xcb_randr_list_output_properties_unchecked';
function xcb_randr_list_output_properties_atoms(R: Pxcb_randr_list_output_properties_reply_t): Pxcb_atom_t; cdecl; external 'xcb-randr' name 'xcb_randr_list_output_properties_atoms';
function xcb_randr_list_output_properties_atoms_length(R: Pxcb_randr_list_output_properties_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_list_output_properties_atoms_length';
{ xcb_randr_list_output_properties_atoms_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_list_output_properties_reply(c: Pxcb_connection_t; cookie: xcb_randr_list_output_properties_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_list_output_properties_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_list_output_properties_reply';
function xcb_randr_query_output_property_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_query_output_property_sizeof';
{ xcb_randr_query_output_property: skipped — parameter type 'xcb_atom_t' comes from a filtered-out header }
{ xcb_randr_query_output_property_unchecked: skipped — parameter type 'xcb_atom_t' comes from a filtered-out header }
function xcb_randr_query_output_property_valid_values(R: Pxcb_randr_query_output_property_reply_t): PInteger; cdecl; external 'xcb-randr' name 'xcb_randr_query_output_property_valid_values';
function xcb_randr_query_output_property_valid_values_length(R: Pxcb_randr_query_output_property_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_query_output_property_valid_values_length';
{ xcb_randr_query_output_property_valid_values_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_query_output_property_reply(c: Pxcb_connection_t; cookie: xcb_randr_query_output_property_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_query_output_property_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_query_output_property_reply';
function xcb_randr_configure_output_property_sizeof(_buffer: Pointer; values_len: Cardinal): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_configure_output_property_sizeof';
{ xcb_randr_configure_output_property_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_configure_output_property: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_randr_configure_output_property_values(R: Pxcb_randr_configure_output_property_request_t): PInteger; cdecl; external 'xcb-randr' name 'xcb_randr_configure_output_property_values';
function xcb_randr_configure_output_property_values_length(R: Pxcb_randr_configure_output_property_request_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_configure_output_property_values_length';
{ xcb_randr_configure_output_property_values_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_change_output_property_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_change_output_property_sizeof';
{ xcb_randr_change_output_property_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_change_output_property: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_randr_change_output_property_data(R: Pxcb_randr_change_output_property_request_t): Pointer; cdecl; external 'xcb-randr' name 'xcb_randr_change_output_property_data';
function xcb_randr_change_output_property_data_length(R: Pxcb_randr_change_output_property_request_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_change_output_property_data_length';
{ xcb_randr_change_output_property_data_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
{ xcb_randr_delete_output_property_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_delete_output_property: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_randr_get_output_property_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_output_property_sizeof';
{ xcb_randr_get_output_property: skipped — parameter type 'xcb_atom_t' comes from a filtered-out header }
{ xcb_randr_get_output_property_unchecked: skipped — parameter type 'xcb_atom_t' comes from a filtered-out header }
function xcb_randr_get_output_property_data(R: Pxcb_randr_get_output_property_reply_t): PByte; cdecl; external 'xcb-randr' name 'xcb_randr_get_output_property_data';
function xcb_randr_get_output_property_data_length(R: Pxcb_randr_get_output_property_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_output_property_data_length';
{ xcb_randr_get_output_property_data_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_output_property_reply(c: Pxcb_connection_t; cookie: xcb_randr_get_output_property_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_get_output_property_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_output_property_reply';
function xcb_randr_create_mode_sizeof(_buffer: Pointer; name_len: Cardinal): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_create_mode_sizeof';
{ xcb_randr_create_mode: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
{ xcb_randr_create_mode_unchecked: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
function xcb_randr_create_mode_reply(c: Pxcb_connection_t; cookie: xcb_randr_create_mode_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_create_mode_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_create_mode_reply';
{ xcb_randr_destroy_mode_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_destroy_mode: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_add_output_mode_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_add_output_mode: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_delete_output_mode_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_delete_output_mode: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_randr_get_crtc_info_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_info_sizeof';
{ xcb_randr_get_crtc_info: skipped — parameter type 'xcb_timestamp_t' comes from a filtered-out header }
{ xcb_randr_get_crtc_info_unchecked: skipped — parameter type 'xcb_timestamp_t' comes from a filtered-out header }
function xcb_randr_get_crtc_info_outputs(R: Pxcb_randr_get_crtc_info_reply_t): Pxcb_randr_output_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_info_outputs';
function xcb_randr_get_crtc_info_outputs_length(R: Pxcb_randr_get_crtc_info_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_info_outputs_length';
{ xcb_randr_get_crtc_info_outputs_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_crtc_info_possible(R: Pxcb_randr_get_crtc_info_reply_t): Pxcb_randr_output_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_info_possible';
function xcb_randr_get_crtc_info_possible_length(R: Pxcb_randr_get_crtc_info_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_info_possible_length';
{ xcb_randr_get_crtc_info_possible_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_crtc_info_reply(c: Pxcb_connection_t; cookie: xcb_randr_get_crtc_info_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_get_crtc_info_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_info_reply';
function xcb_randr_set_crtc_config_sizeof(_buffer: Pointer; outputs_len: Cardinal): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_set_crtc_config_sizeof';
{ xcb_randr_set_crtc_config: skipped — parameter type 'xcb_timestamp_t' comes from a filtered-out header }
{ xcb_randr_set_crtc_config_unchecked: skipped — parameter type 'xcb_timestamp_t' comes from a filtered-out header }
function xcb_randr_set_crtc_config_reply(c: Pxcb_connection_t; cookie: xcb_randr_set_crtc_config_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_set_crtc_config_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_set_crtc_config_reply';
function xcb_randr_get_crtc_gamma_size(c: Pxcb_connection_t; crtc: xcb_randr_crtc_t): xcb_randr_get_crtc_gamma_size_cookie_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_gamma_size';
function xcb_randr_get_crtc_gamma_size_unchecked(c: Pxcb_connection_t; crtc: xcb_randr_crtc_t): xcb_randr_get_crtc_gamma_size_cookie_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_gamma_size_unchecked';
function xcb_randr_get_crtc_gamma_size_reply(c: Pxcb_connection_t; cookie: xcb_randr_get_crtc_gamma_size_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_get_crtc_gamma_size_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_gamma_size_reply';
function xcb_randr_get_crtc_gamma_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_gamma_sizeof';
function xcb_randr_get_crtc_gamma(c: Pxcb_connection_t; crtc: xcb_randr_crtc_t): xcb_randr_get_crtc_gamma_cookie_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_gamma';
function xcb_randr_get_crtc_gamma_unchecked(c: Pxcb_connection_t; crtc: xcb_randr_crtc_t): xcb_randr_get_crtc_gamma_cookie_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_gamma_unchecked';
function xcb_randr_get_crtc_gamma_red(R: Pxcb_randr_get_crtc_gamma_reply_t): PWord; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_gamma_red';
function xcb_randr_get_crtc_gamma_red_length(R: Pxcb_randr_get_crtc_gamma_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_gamma_red_length';
{ xcb_randr_get_crtc_gamma_red_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_crtc_gamma_green(R: Pxcb_randr_get_crtc_gamma_reply_t): PWord; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_gamma_green';
function xcb_randr_get_crtc_gamma_green_length(R: Pxcb_randr_get_crtc_gamma_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_gamma_green_length';
{ xcb_randr_get_crtc_gamma_green_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_crtc_gamma_blue(R: Pxcb_randr_get_crtc_gamma_reply_t): PWord; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_gamma_blue';
function xcb_randr_get_crtc_gamma_blue_length(R: Pxcb_randr_get_crtc_gamma_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_gamma_blue_length';
{ xcb_randr_get_crtc_gamma_blue_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_crtc_gamma_reply(c: Pxcb_connection_t; cookie: xcb_randr_get_crtc_gamma_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_get_crtc_gamma_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_gamma_reply';
function xcb_randr_set_crtc_gamma_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_set_crtc_gamma_sizeof';
{ xcb_randr_set_crtc_gamma_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_set_crtc_gamma: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_randr_set_crtc_gamma_red(R: Pxcb_randr_set_crtc_gamma_request_t): PWord; cdecl; external 'xcb-randr' name 'xcb_randr_set_crtc_gamma_red';
function xcb_randr_set_crtc_gamma_red_length(R: Pxcb_randr_set_crtc_gamma_request_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_set_crtc_gamma_red_length';
{ xcb_randr_set_crtc_gamma_red_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_set_crtc_gamma_green(R: Pxcb_randr_set_crtc_gamma_request_t): PWord; cdecl; external 'xcb-randr' name 'xcb_randr_set_crtc_gamma_green';
function xcb_randr_set_crtc_gamma_green_length(R: Pxcb_randr_set_crtc_gamma_request_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_set_crtc_gamma_green_length';
{ xcb_randr_set_crtc_gamma_green_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_set_crtc_gamma_blue(R: Pxcb_randr_set_crtc_gamma_request_t): PWord; cdecl; external 'xcb-randr' name 'xcb_randr_set_crtc_gamma_blue';
function xcb_randr_set_crtc_gamma_blue_length(R: Pxcb_randr_set_crtc_gamma_request_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_set_crtc_gamma_blue_length';
{ xcb_randr_set_crtc_gamma_blue_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_screen_resources_current_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_resources_current_sizeof';
{ xcb_randr_get_screen_resources_current: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
{ xcb_randr_get_screen_resources_current_unchecked: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
function xcb_randr_get_screen_resources_current_crtcs(R: Pxcb_randr_get_screen_resources_current_reply_t): Pxcb_randr_crtc_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_resources_current_crtcs';
function xcb_randr_get_screen_resources_current_crtcs_length(R: Pxcb_randr_get_screen_resources_current_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_resources_current_crtcs_length';
{ xcb_randr_get_screen_resources_current_crtcs_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_screen_resources_current_outputs(R: Pxcb_randr_get_screen_resources_current_reply_t): Pxcb_randr_output_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_resources_current_outputs';
function xcb_randr_get_screen_resources_current_outputs_length(R: Pxcb_randr_get_screen_resources_current_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_resources_current_outputs_length';
{ xcb_randr_get_screen_resources_current_outputs_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_screen_resources_current_modes(R: Pxcb_randr_get_screen_resources_current_reply_t): Pxcb_randr_mode_info_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_resources_current_modes';
function xcb_randr_get_screen_resources_current_modes_length(R: Pxcb_randr_get_screen_resources_current_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_resources_current_modes_length';
function xcb_randr_get_screen_resources_current_modes_iterator(R: Pxcb_randr_get_screen_resources_current_reply_t): xcb_randr_mode_info_iterator_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_resources_current_modes_iterator';
function xcb_randr_get_screen_resources_current_names(R: Pxcb_randr_get_screen_resources_current_reply_t): PByte; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_resources_current_names';
function xcb_randr_get_screen_resources_current_names_length(R: Pxcb_randr_get_screen_resources_current_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_resources_current_names_length';
{ xcb_randr_get_screen_resources_current_names_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_screen_resources_current_reply(c: Pxcb_connection_t; cookie: xcb_randr_get_screen_resources_current_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_get_screen_resources_current_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_screen_resources_current_reply';
function xcb_randr_set_crtc_transform_sizeof(_buffer: Pointer; filter_params_len: Cardinal): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_set_crtc_transform_sizeof';
{ xcb_randr_set_crtc_transform_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_set_crtc_transform: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_randr_set_crtc_transform_filter_name(R: Pxcb_randr_set_crtc_transform_request_t): PChar; cdecl; external 'xcb-randr' name 'xcb_randr_set_crtc_transform_filter_name';
function xcb_randr_set_crtc_transform_filter_name_length(R: Pxcb_randr_set_crtc_transform_request_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_set_crtc_transform_filter_name_length';
{ xcb_randr_set_crtc_transform_filter_name_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_set_crtc_transform_filter_params(R: Pxcb_randr_set_crtc_transform_request_t): Pxcb_render_fixed_t; cdecl; external 'xcb-randr' name 'xcb_randr_set_crtc_transform_filter_params';
function xcb_randr_set_crtc_transform_filter_params_length(R: Pxcb_randr_set_crtc_transform_request_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_set_crtc_transform_filter_params_length';
{ xcb_randr_set_crtc_transform_filter_params_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_crtc_transform_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_transform_sizeof';
function xcb_randr_get_crtc_transform(c: Pxcb_connection_t; crtc: xcb_randr_crtc_t): xcb_randr_get_crtc_transform_cookie_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_transform';
function xcb_randr_get_crtc_transform_unchecked(c: Pxcb_connection_t; crtc: xcb_randr_crtc_t): xcb_randr_get_crtc_transform_cookie_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_transform_unchecked';
function xcb_randr_get_crtc_transform_pending_filter_name(R: Pxcb_randr_get_crtc_transform_reply_t): PChar; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_transform_pending_filter_name';
function xcb_randr_get_crtc_transform_pending_filter_name_length(R: Pxcb_randr_get_crtc_transform_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_transform_pending_filter_name_length';
{ xcb_randr_get_crtc_transform_pending_filter_name_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_crtc_transform_pending_params(R: Pxcb_randr_get_crtc_transform_reply_t): Pxcb_render_fixed_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_transform_pending_params';
function xcb_randr_get_crtc_transform_pending_params_length(R: Pxcb_randr_get_crtc_transform_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_transform_pending_params_length';
{ xcb_randr_get_crtc_transform_pending_params_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_crtc_transform_current_filter_name(R: Pxcb_randr_get_crtc_transform_reply_t): PChar; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_transform_current_filter_name';
function xcb_randr_get_crtc_transform_current_filter_name_length(R: Pxcb_randr_get_crtc_transform_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_transform_current_filter_name_length';
{ xcb_randr_get_crtc_transform_current_filter_name_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_crtc_transform_current_params(R: Pxcb_randr_get_crtc_transform_reply_t): Pxcb_render_fixed_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_transform_current_params';
function xcb_randr_get_crtc_transform_current_params_length(R: Pxcb_randr_get_crtc_transform_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_transform_current_params_length';
{ xcb_randr_get_crtc_transform_current_params_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_crtc_transform_reply(c: Pxcb_connection_t; cookie: xcb_randr_get_crtc_transform_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_get_crtc_transform_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_crtc_transform_reply';
function xcb_randr_get_panning(c: Pxcb_connection_t; crtc: xcb_randr_crtc_t): xcb_randr_get_panning_cookie_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_panning';
function xcb_randr_get_panning_unchecked(c: Pxcb_connection_t; crtc: xcb_randr_crtc_t): xcb_randr_get_panning_cookie_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_panning_unchecked';
function xcb_randr_get_panning_reply(c: Pxcb_connection_t; cookie: xcb_randr_get_panning_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_get_panning_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_panning_reply';
{ xcb_randr_set_panning: skipped — parameter type 'xcb_timestamp_t' comes from a filtered-out header }
{ xcb_randr_set_panning_unchecked: skipped — parameter type 'xcb_timestamp_t' comes from a filtered-out header }
function xcb_randr_set_panning_reply(c: Pxcb_connection_t; cookie: xcb_randr_set_panning_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_set_panning_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_set_panning_reply';
{ xcb_randr_set_output_primary_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_set_output_primary: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_get_output_primary: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
{ xcb_randr_get_output_primary_unchecked: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
function xcb_randr_get_output_primary_reply(c: Pxcb_connection_t; cookie: xcb_randr_get_output_primary_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_get_output_primary_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_output_primary_reply';
function xcb_randr_get_providers_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_providers_sizeof';
{ xcb_randr_get_providers: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
{ xcb_randr_get_providers_unchecked: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
function xcb_randr_get_providers_providers(R: Pxcb_randr_get_providers_reply_t): Pxcb_randr_provider_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_providers_providers';
function xcb_randr_get_providers_providers_length(R: Pxcb_randr_get_providers_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_providers_providers_length';
{ xcb_randr_get_providers_providers_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_providers_reply(c: Pxcb_connection_t; cookie: xcb_randr_get_providers_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_get_providers_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_providers_reply';
function xcb_randr_get_provider_info_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_provider_info_sizeof';
{ xcb_randr_get_provider_info: skipped — parameter type 'xcb_timestamp_t' comes from a filtered-out header }
{ xcb_randr_get_provider_info_unchecked: skipped — parameter type 'xcb_timestamp_t' comes from a filtered-out header }
function xcb_randr_get_provider_info_crtcs(R: Pxcb_randr_get_provider_info_reply_t): Pxcb_randr_crtc_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_provider_info_crtcs';
function xcb_randr_get_provider_info_crtcs_length(R: Pxcb_randr_get_provider_info_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_provider_info_crtcs_length';
{ xcb_randr_get_provider_info_crtcs_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_provider_info_outputs(R: Pxcb_randr_get_provider_info_reply_t): Pxcb_randr_output_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_provider_info_outputs';
function xcb_randr_get_provider_info_outputs_length(R: Pxcb_randr_get_provider_info_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_provider_info_outputs_length';
{ xcb_randr_get_provider_info_outputs_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_provider_info_associated_providers(R: Pxcb_randr_get_provider_info_reply_t): Pxcb_randr_provider_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_provider_info_associated_providers';
function xcb_randr_get_provider_info_associated_providers_length(R: Pxcb_randr_get_provider_info_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_provider_info_associated_providers_length';
{ xcb_randr_get_provider_info_associated_providers_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_provider_info_associated_capability(R: Pxcb_randr_get_provider_info_reply_t): PCardinal; cdecl; external 'xcb-randr' name 'xcb_randr_get_provider_info_associated_capability';
function xcb_randr_get_provider_info_associated_capability_length(R: Pxcb_randr_get_provider_info_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_provider_info_associated_capability_length';
{ xcb_randr_get_provider_info_associated_capability_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_provider_info_name(R: Pxcb_randr_get_provider_info_reply_t): PChar; cdecl; external 'xcb-randr' name 'xcb_randr_get_provider_info_name';
function xcb_randr_get_provider_info_name_length(R: Pxcb_randr_get_provider_info_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_provider_info_name_length';
{ xcb_randr_get_provider_info_name_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_provider_info_reply(c: Pxcb_connection_t; cookie: xcb_randr_get_provider_info_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_get_provider_info_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_provider_info_reply';
{ xcb_randr_set_provider_offload_sink_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_set_provider_offload_sink: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_set_provider_output_source_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_set_provider_output_source: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_randr_list_provider_properties_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_list_provider_properties_sizeof';
function xcb_randr_list_provider_properties(c: Pxcb_connection_t; provider: xcb_randr_provider_t): xcb_randr_list_provider_properties_cookie_t; cdecl; external 'xcb-randr' name 'xcb_randr_list_provider_properties';
function xcb_randr_list_provider_properties_unchecked(c: Pxcb_connection_t; provider: xcb_randr_provider_t): xcb_randr_list_provider_properties_cookie_t; cdecl; external 'xcb-randr' name 'xcb_randr_list_provider_properties_unchecked';
function xcb_randr_list_provider_properties_atoms(R: Pxcb_randr_list_provider_properties_reply_t): Pxcb_atom_t; cdecl; external 'xcb-randr' name 'xcb_randr_list_provider_properties_atoms';
function xcb_randr_list_provider_properties_atoms_length(R: Pxcb_randr_list_provider_properties_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_list_provider_properties_atoms_length';
{ xcb_randr_list_provider_properties_atoms_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_list_provider_properties_reply(c: Pxcb_connection_t; cookie: xcb_randr_list_provider_properties_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_list_provider_properties_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_list_provider_properties_reply';
function xcb_randr_query_provider_property_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_query_provider_property_sizeof';
{ xcb_randr_query_provider_property: skipped — parameter type 'xcb_atom_t' comes from a filtered-out header }
{ xcb_randr_query_provider_property_unchecked: skipped — parameter type 'xcb_atom_t' comes from a filtered-out header }
function xcb_randr_query_provider_property_valid_values(R: Pxcb_randr_query_provider_property_reply_t): PInteger; cdecl; external 'xcb-randr' name 'xcb_randr_query_provider_property_valid_values';
function xcb_randr_query_provider_property_valid_values_length(R: Pxcb_randr_query_provider_property_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_query_provider_property_valid_values_length';
{ xcb_randr_query_provider_property_valid_values_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_query_provider_property_reply(c: Pxcb_connection_t; cookie: xcb_randr_query_provider_property_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_query_provider_property_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_query_provider_property_reply';
function xcb_randr_configure_provider_property_sizeof(_buffer: Pointer; values_len: Cardinal): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_configure_provider_property_sizeof';
{ xcb_randr_configure_provider_property_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_configure_provider_property: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_randr_configure_provider_property_values(R: Pxcb_randr_configure_provider_property_request_t): PInteger; cdecl; external 'xcb-randr' name 'xcb_randr_configure_provider_property_values';
function xcb_randr_configure_provider_property_values_length(R: Pxcb_randr_configure_provider_property_request_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_configure_provider_property_values_length';
{ xcb_randr_configure_provider_property_values_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_change_provider_property_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_change_provider_property_sizeof';
{ xcb_randr_change_provider_property_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_change_provider_property: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_randr_change_provider_property_data(R: Pxcb_randr_change_provider_property_request_t): Pointer; cdecl; external 'xcb-randr' name 'xcb_randr_change_provider_property_data';
function xcb_randr_change_provider_property_data_length(R: Pxcb_randr_change_provider_property_request_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_change_provider_property_data_length';
{ xcb_randr_change_provider_property_data_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
{ xcb_randr_delete_provider_property_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_delete_provider_property: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_randr_get_provider_property_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_provider_property_sizeof';
{ xcb_randr_get_provider_property: skipped — parameter type 'xcb_atom_t' comes from a filtered-out header }
{ xcb_randr_get_provider_property_unchecked: skipped — parameter type 'xcb_atom_t' comes from a filtered-out header }
function xcb_randr_get_provider_property_data(R: Pxcb_randr_get_provider_property_reply_t): Pointer; cdecl; external 'xcb-randr' name 'xcb_randr_get_provider_property_data';
function xcb_randr_get_provider_property_data_length(R: Pxcb_randr_get_provider_property_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_provider_property_data_length';
{ xcb_randr_get_provider_property_data_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_provider_property_reply(c: Pxcb_connection_t; cookie: xcb_randr_get_provider_property_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_get_provider_property_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_provider_property_reply';
procedure xcb_randr_crtc_change_next(i: Pxcb_randr_crtc_change_iterator_t); cdecl; external 'xcb-randr' name 'xcb_randr_crtc_change_next';
{ xcb_randr_crtc_change_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_randr_output_change_next(i: Pxcb_randr_output_change_iterator_t); cdecl; external 'xcb-randr' name 'xcb_randr_output_change_next';
{ xcb_randr_output_change_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_randr_output_property_next(i: Pxcb_randr_output_property_iterator_t); cdecl; external 'xcb-randr' name 'xcb_randr_output_property_next';
{ xcb_randr_output_property_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_randr_provider_change_next(i: Pxcb_randr_provider_change_iterator_t); cdecl; external 'xcb-randr' name 'xcb_randr_provider_change_next';
{ xcb_randr_provider_change_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_randr_provider_property_next(i: Pxcb_randr_provider_property_iterator_t); cdecl; external 'xcb-randr' name 'xcb_randr_provider_property_next';
{ xcb_randr_provider_property_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_randr_resource_change_next(i: Pxcb_randr_resource_change_iterator_t); cdecl; external 'xcb-randr' name 'xcb_randr_resource_change_next';
{ xcb_randr_resource_change_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_monitor_info_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_monitor_info_sizeof';
function xcb_randr_monitor_info_outputs(R: Pxcb_randr_monitor_info_t): Pxcb_randr_output_t; cdecl; external 'xcb-randr' name 'xcb_randr_monitor_info_outputs';
function xcb_randr_monitor_info_outputs_length(R: Pxcb_randr_monitor_info_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_monitor_info_outputs_length';
{ xcb_randr_monitor_info_outputs_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_randr_monitor_info_next(i: Pxcb_randr_monitor_info_iterator_t); cdecl; external 'xcb-randr' name 'xcb_randr_monitor_info_next';
{ xcb_randr_monitor_info_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
function xcb_randr_get_monitors_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_monitors_sizeof';
{ xcb_randr_get_monitors: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
{ xcb_randr_get_monitors_unchecked: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
function xcb_randr_get_monitors_monitors_length(R: Pxcb_randr_get_monitors_reply_t): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_get_monitors_monitors_length';
function xcb_randr_get_monitors_monitors_iterator(R: Pxcb_randr_get_monitors_reply_t): xcb_randr_monitor_info_iterator_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_monitors_monitors_iterator';
function xcb_randr_get_monitors_reply(c: Pxcb_connection_t; cookie: xcb_randr_get_monitors_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_get_monitors_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_get_monitors_reply';
function xcb_randr_set_monitor_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_set_monitor_sizeof';
{ xcb_randr_set_monitor_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_set_monitor: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_randr_set_monitor_monitorinfo(R: Pxcb_randr_set_monitor_request_t): Pxcb_randr_monitor_info_t; cdecl; external 'xcb-randr' name 'xcb_randr_set_monitor_monitorinfo';
{ xcb_randr_delete_monitor_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_delete_monitor: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_randr_create_lease_sizeof(_buffer: Pointer): Integer; cdecl; external 'xcb-randr' name 'xcb_randr_create_lease_sizeof';
{ xcb_randr_create_lease: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
{ xcb_randr_create_lease_unchecked: skipped — parameter type 'xcb_window_t' comes from a filtered-out header }
function xcb_randr_create_lease_reply(c: Pxcb_connection_t; cookie: xcb_randr_create_lease_cookie_t; e: PPxcb_generic_error_t): Pxcb_randr_create_lease_reply_t; cdecl; external 'xcb-randr' name 'xcb_randr_create_lease_reply';
function xcb_randr_create_lease_reply_fds(c: Pxcb_connection_t; reply: Pxcb_randr_create_lease_reply_t): PInteger; cdecl; external 'xcb-randr' name 'xcb_randr_create_lease_reply_fds';
{ xcb_randr_free_lease_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_randr_free_lease: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
procedure xcb_randr_lease_notify_next(i: Pxcb_randr_lease_notify_iterator_t); cdecl; external 'xcb-randr' name 'xcb_randr_lease_notify_next';
{ xcb_randr_lease_notify_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }
procedure xcb_randr_notify_data_next(i: Pxcb_randr_notify_data_iterator_t); cdecl; external 'xcb-randr' name 'xcb_randr_notify_data_next';
{ xcb_randr_notify_data_end: skipped — return type 'xcb_generic_iterator_t' comes from a filtered-out header }

implementation

end.
