{ Unit Floria.XCB.Cursor — Blaise binding for library 'xcb-cursor'.
  Generated by blaise-bindgen — DO NOT EDIT.
  Regenerate with:  bindgen --header <header.h> --unit Floria.XCB.Cursor --lib xcb-cursor }

unit Floria.XCB.Cursor;
{$mode objfpc}{$H+}

interface

uses
  Floria.XCB;

type
  Pxcb_connection_t = ^xcb_connection_t;
  Pxcb_screen_t = ^xcb_screen_t;
  Pxcb_cursor_context_t = ^xcb_cursor_context_t;
  PPxcb_cursor_context_t = ^Pxcb_cursor_context_t;
  xcb_cursor_context_t = record end; { opaque }

function xcb_cursor_context_new(conn: Pxcb_connection_t; screen: Pxcb_screen_t; ctx: PPxcb_cursor_context_t): Integer; cdecl; external 'xcb-cursor' name 'xcb_cursor_context_new';
{ xcb_cursor_load_cursor: skipped — return type 'xcb_cursor_t' comes from a filtered-out header }
procedure xcb_cursor_context_free(ctx: Pxcb_cursor_context_t); cdecl; external 'xcb-cursor' name 'xcb_cursor_context_free';

implementation

end.
