{ Unit Floria.XCB.EWMH — Blaise binding for library 'xcb-ewmh'.
  Generated by blaise-bindgen — DO NOT EDIT.
  Regenerate with:  bindgen --header <header.h> --unit Floria.XCB.EWMH --lib xcb-ewmh }

unit Floria.XCB.EWMH;
{$mode objfpc}{$H+}

interface

uses
  Floria.XCB;

type
  Pxcb_connection_t = ^xcb_connection_t;
  Pxcb_screen_t = ^xcb_screen_t;
  PPxcb_screen_t = ^Pxcb_screen_t;
  Pxcb_atom_t = ^xcb_atom_t;
  Pxcb_get_property_reply_t = ^xcb_get_property_reply_t;
  Pxcb_window_t = ^xcb_window_t;
  Pxcb_ewmh_coordinates_t = ^xcb_ewmh_coordinates_t;
  Pxcb_ewmh_geometry_t = ^xcb_ewmh_geometry_t;
  PCardinal = ^Cardinal;
  Pxcb_intern_atom_cookie_t = ^xcb_intern_atom_cookie_t;
  Pxcb_ewmh_connection_t = ^xcb_ewmh_connection_t;
  Pxcb_generic_error_t = ^xcb_generic_error_t;
  PPxcb_generic_error_t = ^Pxcb_generic_error_t;
  Pxcb_ewmh_get_atoms_reply_t = ^xcb_ewmh_get_atoms_reply_t;
  Pxcb_ewmh_get_windows_reply_t = ^xcb_ewmh_get_windows_reply_t;
  Pxcb_ewmh_get_utf8_strings_reply_t = ^xcb_ewmh_get_utf8_strings_reply_t;
  Pxcb_ewmh_get_desktop_viewport_reply_t = ^xcb_ewmh_get_desktop_viewport_reply_t;
  Pxcb_ewmh_get_workarea_reply_t = ^xcb_ewmh_get_workarea_reply_t;
  Pxcb_ewmh_get_desktop_layout_reply_t = ^xcb_ewmh_get_desktop_layout_reply_t;
  Pxcb_ewmh_get_extents_reply_t = ^xcb_ewmh_get_extents_reply_t;
  Pxcb_ewmh_wm_strut_partial_t = ^xcb_ewmh_wm_strut_partial_t;
  Pxcb_ewmh_get_wm_icon_reply_t = ^xcb_ewmh_get_wm_icon_reply_t;
  Pxcb_ewmh_wm_icon_iterator_t = ^xcb_ewmh_wm_icon_iterator_t;
  PUInt64 = ^UInt64;
  Pxcb_ewmh_get_wm_fullscreen_monitors_reply_t = ^xcb_ewmh_get_wm_fullscreen_monitors_reply_t;
  Pxcb_get_selection_owner_reply_t = ^xcb_get_selection_owner_reply_t;
  xcb_ewmh_connection_t = record
    connection: Pxcb_connection_t;
    screens: PPxcb_screen_t;
    nb_screens: Integer;
    _NET_WM_CM_Sn: Pxcb_atom_t;
    _NET_SUPPORTED: xcb_atom_t;
    _NET_CLIENT_LIST: xcb_atom_t;
    _NET_CLIENT_LIST_STACKING: xcb_atom_t;
    _NET_NUMBER_OF_DESKTOPS: xcb_atom_t;
    _NET_DESKTOP_GEOMETRY: xcb_atom_t;
    _NET_DESKTOP_VIEWPORT: xcb_atom_t;
    _NET_CURRENT_DESKTOP: xcb_atom_t;
    _NET_DESKTOP_NAMES: xcb_atom_t;
    _NET_ACTIVE_WINDOW: xcb_atom_t;
    _NET_WORKAREA: xcb_atom_t;
    _NET_SUPPORTING_WM_CHECK: xcb_atom_t;
    _NET_VIRTUAL_ROOTS: xcb_atom_t;
    _NET_DESKTOP_LAYOUT: xcb_atom_t;
    _NET_SHOWING_DESKTOP: xcb_atom_t;
    _NET_CLOSE_WINDOW: xcb_atom_t;
    _NET_MOVERESIZE_WINDOW: xcb_atom_t;
    _NET_WM_MOVERESIZE: xcb_atom_t;
    _NET_RESTACK_WINDOW: xcb_atom_t;
    _NET_REQUEST_FRAME_EXTENTS: xcb_atom_t;
    _NET_WM_NAME: xcb_atom_t;
    _NET_WM_VISIBLE_NAME: xcb_atom_t;
    _NET_WM_ICON_NAME: xcb_atom_t;
    _NET_WM_VISIBLE_ICON_NAME: xcb_atom_t;
    _NET_WM_DESKTOP: xcb_atom_t;
    _NET_WM_WINDOW_TYPE: xcb_atom_t;
    _NET_WM_STATE: xcb_atom_t;
    _NET_WM_ALLOWED_ACTIONS: xcb_atom_t;
    _NET_WM_STRUT: xcb_atom_t;
    _NET_WM_STRUT_PARTIAL: xcb_atom_t;
    _NET_WM_ICON_GEOMETRY: xcb_atom_t;
    _NET_WM_ICON: xcb_atom_t;
    _NET_WM_PID: xcb_atom_t;
    _NET_WM_HANDLED_ICONS: xcb_atom_t;
    _NET_WM_USER_TIME: xcb_atom_t;
    _NET_WM_USER_TIME_WINDOW: xcb_atom_t;
    _NET_FRAME_EXTENTS: xcb_atom_t;
    _NET_WM_PING: xcb_atom_t;
    _NET_WM_SYNC_REQUEST: xcb_atom_t;
    _NET_WM_SYNC_REQUEST_COUNTER: xcb_atom_t;
    _NET_WM_FULLSCREEN_MONITORS: xcb_atom_t;
    _NET_WM_FULL_PLACEMENT: xcb_atom_t;
    UTF8_STRING: xcb_atom_t;
    WM_PROTOCOLS: xcb_atom_t;
    MANAGER: xcb_atom_t;
    _NET_WM_WINDOW_TYPE_DESKTOP: xcb_atom_t;
    _NET_WM_WINDOW_TYPE_DOCK: xcb_atom_t;
    _NET_WM_WINDOW_TYPE_TOOLBAR: xcb_atom_t;
    _NET_WM_WINDOW_TYPE_MENU: xcb_atom_t;
    _NET_WM_WINDOW_TYPE_UTILITY: xcb_atom_t;
    _NET_WM_WINDOW_TYPE_SPLASH: xcb_atom_t;
    _NET_WM_WINDOW_TYPE_DIALOG: xcb_atom_t;
    _NET_WM_WINDOW_TYPE_DROPDOWN_MENU: xcb_atom_t;
    _NET_WM_WINDOW_TYPE_POPUP_MENU: xcb_atom_t;
    _NET_WM_WINDOW_TYPE_TOOLTIP: xcb_atom_t;
    _NET_WM_WINDOW_TYPE_NOTIFICATION: xcb_atom_t;
    _NET_WM_WINDOW_TYPE_COMBO: xcb_atom_t;
    _NET_WM_WINDOW_TYPE_DND: xcb_atom_t;
    _NET_WM_WINDOW_TYPE_NORMAL: xcb_atom_t;
    _NET_WM_STATE_MODAL: xcb_atom_t;
    _NET_WM_STATE_STICKY: xcb_atom_t;
    _NET_WM_STATE_MAXIMIZED_VERT: xcb_atom_t;
    _NET_WM_STATE_MAXIMIZED_HORZ: xcb_atom_t;
    _NET_WM_STATE_SHADED: xcb_atom_t;
    _NET_WM_STATE_SKIP_TASKBAR: xcb_atom_t;
    _NET_WM_STATE_SKIP_PAGER: xcb_atom_t;
    _NET_WM_STATE_HIDDEN: xcb_atom_t;
    _NET_WM_STATE_FULLSCREEN: xcb_atom_t;
    _NET_WM_STATE_ABOVE: xcb_atom_t;
    _NET_WM_STATE_BELOW: xcb_atom_t;
    _NET_WM_STATE_DEMANDS_ATTENTION: xcb_atom_t;
    _NET_WM_ACTION_MOVE: xcb_atom_t;
    _NET_WM_ACTION_RESIZE: xcb_atom_t;
    _NET_WM_ACTION_MINIMIZE: xcb_atom_t;
    _NET_WM_ACTION_SHADE: xcb_atom_t;
    _NET_WM_ACTION_STICK: xcb_atom_t;
    _NET_WM_ACTION_MAXIMIZE_HORZ: xcb_atom_t;
    _NET_WM_ACTION_MAXIMIZE_VERT: xcb_atom_t;
    _NET_WM_ACTION_FULLSCREEN: xcb_atom_t;
    _NET_WM_ACTION_CHANGE_DESKTOP: xcb_atom_t;
    _NET_WM_ACTION_CLOSE: xcb_atom_t;
    _NET_WM_ACTION_ABOVE: xcb_atom_t;
    _NET_WM_ACTION_BELOW: xcb_atom_t;
  end;
  xcb_ewmh_get_atoms_reply_t = record
    atoms_len: Cardinal;
    atoms: Pxcb_atom_t;
    _reply: Pxcb_get_property_reply_t;
  end;
  xcb_ewmh_get_windows_reply_t = record
    windows_len: Cardinal;
    windows: Pxcb_window_t;
    _reply: Pxcb_get_property_reply_t;
  end;
  xcb_ewmh_get_utf8_strings_reply_t = record
    strings_len: Cardinal;
    strings: PChar;
    _reply: Pxcb_get_property_reply_t;
  end;
  xcb_ewmh_coordinates_t = record
    x: Cardinal;
    y: Cardinal;
  end;
  xcb_ewmh_get_desktop_viewport_reply_t = record
    desktop_viewport_len: Cardinal;
    desktop_viewport: Pxcb_ewmh_coordinates_t;
    _reply: Pxcb_get_property_reply_t;
  end;
  xcb_ewmh_geometry_t = record
    x: Cardinal;
    y: Cardinal;
    width: Cardinal;
    height: Cardinal;
  end;
  xcb_ewmh_get_workarea_reply_t = record
    workarea_len: Cardinal;
    workarea: Pxcb_ewmh_geometry_t;
    _reply: Pxcb_get_property_reply_t;
  end;
  xcb_ewmh_client_source_type_t = Integer;
  xcb_ewmh_desktop_layout_orientation_t = Integer;
  xcb_ewmh_desktop_layout_starting_corner_t = Integer;
  xcb_ewmh_get_desktop_layout_reply_t = record
    orientation: Cardinal;
    columns: Cardinal;
    rows: Cardinal;
    starting_corner: Cardinal;
  end;
  xcb_ewmh_moveresize_window_opt_flags_t = Integer;
  xcb_ewmh_moveresize_direction_t = Integer;
  xcb_ewmh_wm_state_action_t = Integer;
  xcb_ewmh_wm_strut_partial_t = record
    left: Cardinal;
    right: Cardinal;
    top: Cardinal;
    bottom: Cardinal;
    left_start_y: Cardinal;
    left_end_y: Cardinal;
    right_start_y: Cardinal;
    right_end_y: Cardinal;
    top_start_x: Cardinal;
    top_end_x: Cardinal;
    bottom_start_x: Cardinal;
    bottom_end_x: Cardinal;
  end;
  xcb_ewmh_wm_icon_iterator_t = record
    width: Cardinal;
    height: Cardinal;
    data: PCardinal;
    rem: Cardinal;
    index: Cardinal;
  end;
  xcb_ewmh_get_wm_icon_reply_t = record
    num_icons: Cardinal;
    _reply: Pxcb_get_property_reply_t;
  end;
  xcb_ewmh_get_extents_reply_t = record
    left: Cardinal;
    right: Cardinal;
    top: Cardinal;
    bottom: Cardinal;
  end;
  xcb_ewmh_get_wm_fullscreen_monitors_reply_t = record
    top: Cardinal;
    bottom: Cardinal;
    left: Cardinal;
    right: Cardinal;
  end;

const
  XCB_EWMH_CLIENT_SOURCE_TYPE_NONE = 0;
  XCB_EWMH_CLIENT_SOURCE_TYPE_NORMAL = 1;
  XCB_EWMH_CLIENT_SOURCE_TYPE_OTHER = 2;
  XCB_EWMH_WM_ORIENTATION_HORZ = 0;
  XCB_EWMH_WM_ORIENTATION_VERT = 1;
  XCB_EWMH_WM_TOPLEFT = 0;
  XCB_EWMH_WM_TOPRIGHT = 1;
  XCB_EWMH_WM_BOTTOMRIGHT = 2;
  XCB_EWMH_WM_BOTTOMLEFT = 3;
  XCB_EWMH_MOVERESIZE_WINDOW_X = 256;
  XCB_EWMH_MOVERESIZE_WINDOW_Y = 512;
  XCB_EWMH_MOVERESIZE_WINDOW_WIDTH = 1024;
  XCB_EWMH_MOVERESIZE_WINDOW_HEIGHT = 2048;
  XCB_EWMH_WM_MOVERESIZE_SIZE_TOPLEFT = 0;
  XCB_EWMH_WM_MOVERESIZE_SIZE_TOP = 1;
  XCB_EWMH_WM_MOVERESIZE_SIZE_TOPRIGHT = 2;
  XCB_EWMH_WM_MOVERESIZE_SIZE_RIGHT = 3;
  XCB_EWMH_WM_MOVERESIZE_SIZE_BOTTOMRIGHT = 4;
  XCB_EWMH_WM_MOVERESIZE_SIZE_BOTTOM = 5;
  XCB_EWMH_WM_MOVERESIZE_SIZE_BOTTOMLEFT = 6;
  XCB_EWMH_WM_MOVERESIZE_SIZE_LEFT = 7;
  XCB_EWMH_WM_MOVERESIZE_MOVE = 8;
  XCB_EWMH_WM_MOVERESIZE_SIZE_KEYBOARD = 9;
  XCB_EWMH_WM_MOVERESIZE_MOVE_KEYBOARD = 10;
  XCB_EWMH_WM_MOVERESIZE_CANCEL = 11;
  XCB_EWMH_WM_STATE_REMOVE = 0;
  XCB_EWMH_WM_STATE_ADD = 1;
  XCB_EWMH_WM_STATE_TOGGLE = 2;

function xcb_ewmh_init_atoms(c: Pxcb_connection_t; ewmh: Pxcb_ewmh_connection_t): Pxcb_intern_atom_cookie_t; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_init_atoms';
function xcb_ewmh_init_atoms_replies(ewmh: Pxcb_ewmh_connection_t; ewmh_cookies: Pxcb_intern_atom_cookie_t; e: PPxcb_generic_error_t): Byte; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_init_atoms_replies';
{ xcb_ewmh_send_client_message: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_ewmh_get_window_from_reply(window: Pxcb_window_t; r: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_window_from_reply';
{ xcb_ewmh_get_window_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
function xcb_ewmh_get_cardinal_from_reply(cardinal: PCardinal; r: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_cardinal_from_reply';
{ xcb_ewmh_get_cardinal_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
function xcb_ewmh_get_atoms_from_reply(atoms: Pxcb_ewmh_get_atoms_reply_t; r: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_atoms_from_reply';
{ xcb_ewmh_get_atoms_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
procedure xcb_ewmh_get_atoms_reply_wipe(data: Pxcb_ewmh_get_atoms_reply_t); cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_atoms_reply_wipe';
function xcb_ewmh_get_windows_from_reply(atoms: Pxcb_ewmh_get_windows_reply_t; r: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_windows_from_reply';
function xcb_ewmh_get_utf8_strings_from_reply(ewmh: Pxcb_ewmh_connection_t; data: Pxcb_ewmh_get_utf8_strings_reply_t; r: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_utf8_strings_from_reply';
{ xcb_ewmh_get_utf8_strings_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_windows_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
procedure xcb_ewmh_get_windows_reply_wipe(data: Pxcb_ewmh_get_windows_reply_t); cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_windows_reply_wipe';
procedure xcb_ewmh_get_utf8_strings_reply_wipe(data: Pxcb_ewmh_get_utf8_strings_reply_t); cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_utf8_strings_reply_wipe';
{ xcb_ewmh_set_supported: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_supported_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_supported_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_supported: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_client_list: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_client_list_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_client_list_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_client_list: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_client_list_stacking: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_client_list_stacking_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_client_list_stacking_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_client_list_stacking: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_number_of_desktops: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_number_of_desktops_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_number_of_desktops_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_number_of_desktops: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_desktop_geometry: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_desktop_geometry_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_desktop_geometry_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_desktop_geometry: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_request_change_desktop_geometry: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_ewmh_get_desktop_geometry_from_reply(width: PCardinal; height: PCardinal; r: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_desktop_geometry_from_reply';
{ xcb_ewmh_get_desktop_geometry_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_desktop_viewport: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_desktop_viewport_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_desktop_viewport_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_desktop_viewport: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_request_change_desktop_viewport: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
function xcb_ewmh_get_desktop_viewport_from_reply(vp: Pxcb_ewmh_get_desktop_viewport_reply_t; r: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_desktop_viewport_from_reply';
{ xcb_ewmh_get_desktop_viewport_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
procedure xcb_ewmh_get_desktop_viewport_reply_wipe(r: Pxcb_ewmh_get_desktop_viewport_reply_t); cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_desktop_viewport_reply_wipe';
{ xcb_ewmh_set_current_desktop: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_current_desktop_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_current_desktop_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_current_desktop: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_request_change_current_desktop: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_desktop_names: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_desktop_names_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_desktop_names_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_desktop_names: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_active_window: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_active_window_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_request_change_active_window: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_active_window_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_active_window: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_workarea: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_workarea_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_workarea_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_workarea: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
function xcb_ewmh_get_workarea_from_reply(wa: Pxcb_ewmh_get_workarea_reply_t; r: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_workarea_from_reply';
{ xcb_ewmh_get_workarea_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
procedure xcb_ewmh_get_workarea_reply_wipe(r: Pxcb_ewmh_get_workarea_reply_t); cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_workarea_reply_wipe';
{ xcb_ewmh_set_supporting_wm_check: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_supporting_wm_check_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_supporting_wm_check_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_supporting_wm_check: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_virtual_roots: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_virtual_roots_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_virtual_roots_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_virtual_roots: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_desktop_layout: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_desktop_layout_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_desktop_layout_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_desktop_layout: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
function xcb_ewmh_get_desktop_layout_from_reply(desktop_layouts: Pxcb_ewmh_get_desktop_layout_reply_t; r: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_desktop_layout_from_reply';
{ xcb_ewmh_get_desktop_layout_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_showing_desktop: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_showing_desktop_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_showing_desktop_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_showing_desktop: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_request_close_window: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_request_moveresize_window: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_request_wm_moveresize: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_request_restack_window: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_name: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_name_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_name_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_name: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_visible_name: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_visible_name_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_visible_name_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_visible_name: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_icon_name: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_icon_name_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_icon_name_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_icon_name: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_visible_icon_name: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_visible_icon_name_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_visible_icon_name_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_visible_icon_name: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_desktop: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_desktop_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_desktop_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_desktop: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_request_change_wm_desktop: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_window_type: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_window_type_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_window_type_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_window_type: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
function xcb_ewmh_get_wm_window_type_from_reply(wtypes: Pxcb_ewmh_get_atoms_reply_t; r: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_wm_window_type_from_reply';
{ xcb_ewmh_get_wm_window_type_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_state: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_state_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_state_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_state: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
function xcb_ewmh_get_wm_state_from_reply(wtypes: Pxcb_ewmh_get_atoms_reply_t; r: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_wm_state_from_reply';
{ xcb_ewmh_get_wm_state_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_request_change_wm_state: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_allowed_actions: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_allowed_actions_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_allowed_actions_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_allowed_actions: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
function xcb_ewmh_get_wm_allowed_actions_from_reply(wtypes: Pxcb_ewmh_get_atoms_reply_t; r: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_wm_allowed_actions_from_reply';
{ xcb_ewmh_get_wm_allowed_actions_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_strut: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_strut_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_strut_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_strut: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
function xcb_ewmh_get_wm_strut_from_reply(struts: Pxcb_ewmh_get_extents_reply_t; r: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_wm_strut_from_reply';
{ xcb_ewmh_get_wm_strut_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_strut_partial: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_strut_partial_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_strut_partial_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_strut_partial: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
function xcb_ewmh_get_wm_strut_partial_from_reply(struts: Pxcb_ewmh_wm_strut_partial_t; r: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_wm_strut_partial_from_reply';
{ xcb_ewmh_get_wm_strut_partial_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_icon_geometry: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_icon_geometry_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_icon_geometry_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_icon_geometry: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
function xcb_ewmh_get_wm_icon_geometry_from_reply(icons: Pxcb_ewmh_geometry_t; r: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_wm_icon_geometry_from_reply';
{ xcb_ewmh_get_wm_icon_geometry_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_append_wm_icon_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_append_wm_icon: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_icon_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_icon: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
function xcb_ewmh_get_wm_icon_from_reply(wm_icon: Pxcb_ewmh_get_wm_icon_reply_t; r: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_wm_icon_from_reply';
{ xcb_ewmh_get_wm_icon_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
function xcb_ewmh_get_wm_icon_iterator(wm_icon: Pxcb_ewmh_get_wm_icon_reply_t): xcb_ewmh_wm_icon_iterator_t; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_wm_icon_iterator';
function xcb_ewmh_get_wm_icon_length(wm_icon: Pxcb_ewmh_get_wm_icon_reply_t): Cardinal; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_wm_icon_length';
procedure xcb_ewmh_get_wm_icon_next(iterator: Pxcb_ewmh_wm_icon_iterator_t); cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_wm_icon_next';
procedure xcb_ewmh_get_wm_icon_reply_wipe(wm_icon: Pxcb_ewmh_get_wm_icon_reply_t); cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_wm_icon_reply_wipe';
{ xcb_ewmh_set_wm_pid: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_pid_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_pid_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_pid: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_handled_icons: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_handled_icons_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_handled_icons_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_handled_icons: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_user_time: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_user_time_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_user_time_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_user_time: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_user_time_window: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_user_time_window_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_user_time_window_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_user_time_window: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_frame_extents: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_frame_extents_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_frame_extents_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_frame_extents: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
function xcb_ewmh_get_frame_extents_from_reply(frame_extents: Pxcb_ewmh_get_extents_reply_t; r: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_frame_extents_from_reply';
{ xcb_ewmh_get_frame_extents_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_send_wm_ping: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_sync_request_counter: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_sync_request_counter_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_sync_request_counter_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_sync_request_counter: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
function xcb_ewmh_get_wm_sync_request_counter_from_reply(counter: PUInt64; r: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_wm_sync_request_counter_from_reply';
{ xcb_ewmh_get_wm_sync_request_counter_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_send_wm_sync_request: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_fullscreen_monitors: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_fullscreen_monitors_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_fullscreen_monitors_unchecked: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_fullscreen_monitors: skipped — return type 'xcb_get_property_cookie_t' comes from a filtered-out header }
function xcb_ewmh_get_wm_fullscreen_monitors_from_reply(monitors: Pxcb_ewmh_get_wm_fullscreen_monitors_reply_t; r: Pxcb_get_property_reply_t): Byte; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_wm_fullscreen_monitors_from_reply';
{ xcb_ewmh_get_wm_fullscreen_monitors_reply: skipped — parameter type 'xcb_get_property_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_request_change_wm_fullscreen_monitors: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_cm_owner: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_set_wm_cm_owner_checked: skipped — return type 'xcb_void_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_cm_owner_unchecked: skipped — return type 'xcb_get_selection_owner_cookie_t' comes from a filtered-out header }
{ xcb_ewmh_get_wm_cm_owner: skipped — return type 'xcb_get_selection_owner_cookie_t' comes from a filtered-out header }
function xcb_ewmh_get_wm_cm_owner_from_reply(owner: Pxcb_window_t; r: Pxcb_get_selection_owner_reply_t): Byte; cdecl; external 'xcb-ewmh' name 'xcb_ewmh_get_wm_cm_owner_from_reply';
{ xcb_ewmh_get_wm_cm_owner_reply: skipped — parameter type 'xcb_get_selection_owner_cookie_t' comes from a filtered-out header }

implementation

end.
